### ISSUE TITLE
Item

### ISSUE THREAD

**Issue by Znakeyboy** [rockyhawk64/CommandPanels#1]
Hi! Im wondering how i make a click able item in the hot bar with CommandPanels and when players click inside a menu they get an rank i use Group Manager
![2020-07-02_12 30 26](https://user-images.githubusercontent.com/67738632/86348465-fe256500-bc5f-11ea-97e8-b2d49b7a0cec.png)

**Comment by Znakeyboy** [comment]
I know about the ScoreBoard im not done yet

**Comment by Znakeyboy** [comment]
Forget i figured it out

**Comment by rockyhawk64** [comment]
For anyone who clicks this also wondering how to do this, visit here: [https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/hotbar-items](here)
