### ISSUE TITLE
Commands on close

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#10]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A line just like commands-on-open, to execute commands on panel close

**Describe alternatives you've considered**
Does not apply

**Additional context**
This suggestion is transferred to github. Original idea is from HamDatNoob#5773
This is a **NON** patreon suggestion.

**Comment by rockyhawk64** [comment]
Won't be adding currently. Will reopen if otherwise.
