### ISSUE TITLE
Custom item paywall amounts.

### ISSUE THREAD

**Issue by PiglerthePig** [rockyhawk64/CommandPanels#102]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes
### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem? Please describe.
It is not part of a problem.

### Describe the solution you'd like
I would like to be able to use multiple custom item requirements in an item pay wall, aswell as, being able to use multiple amounts of that item.

### Describe alternatives you've considered
I have not decided on any alternatives.

### Additional context
- item-paywall= wooden_planks
- item-paywall= wooden_handle
I have tried the above ^, but it seems that it would start with the top, "- item-paywall= wooden_planks", then to the next pay wall, this would take the player's wooden planks item, even if they do not have a wooden handle item, i would also like the use of "- item-paywall= wooden_planks 2" for custom amounts of a required custom item.

**Comment by fireFerry** [comment]
Amounts already are a thing, and you can also make multiple requirements with hasvalue and placeholders.

**Comment by PiglerthePig** [comment]
> Amounts already are a thing, and you can also make multiple requirements with hasvalue and placeholders.

amounts do not seem to be a thing for item paywalls for custom items, it sends me a error message in chat. I will try around with hasvalue and placeholders.

**Comment by rockyhawk64** [comment]
> > Amounts already are a thing, and you can also make multiple requirements with hasvalue and placeholders.
> 
> amounts do not seem to be a thing for item paywalls for custom items, it sends me a error message in chat. I will try around with hasvalue and placeholders.

It should be working. You need to add a stack size to the custom item like this:
```YAML
custom-item:
  dagger1:
    material: mmo= example dagger
    stack: 3
```

**Comment by PiglerthePig** [comment]
> > > Amounts already are a thing, and you can also make multiple requirements with hasvalue and placeholders.
> > 
> > 
> > amounts do not seem to be a thing for item paywalls for custom items, it sends me a error message in chat. I will try around with hasvalue and placeholders.
> 
> It should be working. You need to add a stack size to the custom item like this:
> 
> ```yaml
> custom-item:
>   dagger1:
>     material: mmo= example dagger
>     stack: 3
> ```

i did try this, which i did not mention.It will take 3 daggers, but will accept any amount below that i think, i only tried with stack: 2 and it did take just one, before moving on to the next command in the list

**Comment by PiglerthePig** [comment]
i think i somewhat achieved what i wanted for my custom crafting in command panels by just using the checkitem placeholder and a few hasvalues. I guess this can be closed now.
