### ISSUE TITLE
[ INGAME EDITOR ] Command Removal

### ISSUE THREAD

**Issue by MeerBiene** [rockyhawk64/CommandPanels#103]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.

No, not related to any problem, just a change that would bring more convenience.

### Describe the solution you'd like

When removing commands from an item in the ingame editor, it would be pretty neat to have the option to pass in multiple number, so e.g. "1,2" or if you want to specify a range, you could do "1-4" (range was not my Idea I think it was Fireferry and credit where credit belongs.)

### Describe alternatives you've considered

If I knew Java I would have opened a Pull Request :(

### Additional context

Whoever is reading this, have a nice day, take care and stay healthy 😷

**Comment by rockyhawk64** [comment]
It will not be added to the editor but if the editor is recoded from scratch this will be re-opened.
