### ISSUE TITLE
Checking if item inhand is broken with a placeholder (instead of a slot number)

### ISSUE THREAD

**Issue by Bloodlex** [rockyhawk64/CommandPanels#104]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
I'm frustrated trying to check if an item hold in hand needs repairs. I don't know the slot number tha player would hold that.

I'm using essentialsX command "repair inhand" and would like to be charged only when an item really needs repair.

I know this placeholder, but it only accepts slot number:

%cp-damaged-<slot>%
Choose a slot in the panel for the int, it will return true if the item you chose is damaged, false if it is not.

### Describe the solution you'd like
I would like to have an **option like "inhand" or "hand" instead of <slot> number like %cp-damaged-inhand%**

### Describe alternatives you've considered
Already tried with different placeholders, trying to give "hand" or "inhand" instead of slot number, but nothing worked.

**Comment by rockyhawk64** [comment]
Unfortunately, this will not be added because that placeholder is designed to be used for slots only, eg for the panel slots only, not the player's inventory slots. An alternative is to allow the player to place an item in the panel and then check the slot that the player places the item in.
