### ISSUE TITLE
Banner HideFlags not working

### ISSUE THREAD

**Issue by pintoso** [rockyhawk64/CommandPanels#105]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
`HideFlags` does not work with banners 

### To Reproduce
1. `/minecraft:give @p minecraft:black_banner{HideFlags:32,BlockEntityTag:{Patterns:[{Pattern:bs,Color:14},{Pattern:ls,Color:14},{Pattern:bo,Color:15}]}} 1`
2. put the item in the chest 
3. `/cpg`, and open the chest
4. `/cp <pane>`

### Expected behavior
The plugin keep the list of banner patterns hidden 

### Screenshots/videos

https://user-images.githubusercontent.com/26844778/108798561-d1b2b600-756c-11eb-8883-6413a92310ed.mp4

### Versions:
 - Minecraft: 1.16.4 paper #404
 - CommandPanels: 3.15.2.4

**Comment by fireFerry** [comment]
This isn't a bug, There are specific item types found on the wiki you can use.
https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#item-type

**Comment by pintoso** [comment]
> This isn't a bug, There are specific item types found on the wiki you can use.
> https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#item-type

did you test it and did it work for you?
because I had already read the wiki and tested it..
anyway I tested it again now and it doesn't work with banners

**Comment by rockyhawk64** [comment]
https://github.com/rockyhawk64/CommandPanels/projects/6#card-56146373
