### ISSUE TITLE
Adding in unbreaking for custom models

### ISSUE THREAD

**Issue by DizCraft** [rockyhawk64/CommandPanels#106]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
Being able to add in unbreakable to custom items when using the "Damage: x"

### Additional context
I run a server "pre-Custom_Model_Data" with over 500+ models. I do not wish to rewrite the entire server but would love to be able to have the hideous damage bar (yellow bar on damaged items) to not be visible as it is an eyesore.

i.e something that can trigger in itemmeta:
.setUnbreakable(true);

**Comment by rockyhawk64** [comment]
In the new update (v3.15.3.0) if you add this to an item, it will make it unbreakable:
`damage: -1`

**Comment by DizCraft** [comment]
This kinda negates what was intented.

As if I wanted to display a 3D model on a Golden_shovel with 19 durability....
I cant set "damage: -1" or it'll just show the default item and not the 3D model.

Why not just make
"unbreaking: [true/false]"?
