### ISSUE TITLE
Suggestion: Book author and type when written book as material and title= as command

### ISSUE THREAD

**Issue by Luncaaa** [rockyhawk64/CommandPanels#109]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes, I was told I could make a suggestion here for the title thing.

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Not a problem, a suggestion.

### Describe the solution you'd like
Adding author and type on written boom material and title= in command section.

### Describe alternatives you've considered
My idea is adding author and type when having WRITTEN_BOOK as material and in commands, an option that is title= <anything> so it changes menu's title

### Additional context
Well so my suggestions are adding author and type when you have written book as material. It would be something like:
material: WRITTEN_BOOK
author: 'hello' (and you can use color codes too)
type: ORIGINAL / COPY_OF_ORIGINAL....

And also being able to add title= on commands section so it edits the menu's title. Something like:
Commands:
msg= &aHello
title= &cI say hello to you (or anything)
Or maybe even for some time (in ticks or seconds)
title= &cI say hello to you;100 (; would separate  title from time, and 100 would be time you have that title in ticks before changing to that panel's original title)

I hope this can be added :)
~Luca

**Comment by rockyhawk64** [comment]
If you use the `book= <author>` material tag, it is on the wiki [here](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#material)
You can do something like this:
```YAML
material: book= RockyHawk
name: name of the book
lore:
- books lore
write:
- this text will show up inside of the book if it was opened
```

**Comment by Luncaaa** [comment]
Oh, sorry, didn't see that. What about the type? Like original, copy of original etc

**Comment by rockyhawk64** [comment]
There is no settings in cp for original / copy of original.
