### ISSUE TITLE
Player Head textures not showing up

### ISSUE THREAD

**Issue by MatchGames** [rockyhawk64/CommandPanels#11]
**Describe the Issue**
When I put heads (That aren't steve nor alex heads) they turn into Steve heads instead of the texture expected.

**Screenshots**
https://drive.google.com/file/d/13qyL_iKB_DBk2dZZxuE8VUFGda-xcHmW/view

**Versions:**
 - Minecraft: 1.12.2
 - CommandPanels: 2.9.3-classic

**Comment by fireFerry** [comment]
Hello! How did you get those heads? from the HeadDatabase plugin?

**Comment by MatchGames** [comment]
No, I got the heads from commands/commandblocks. From the minecraft-heads.com site.

**Comment by fireFerry** [comment]
Okay, currently you can't put those heads in in-game you will need to add the value of the heads to the material in the panel config. How to do so is explained here: https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-tags#material-tags

**Comment by MatchGames** [comment]
Do I have to do that if I was using HeadDatabase?

**Comment by fireFerry** [comment]
No, HeadDatabase heads can be put into the GUI, but not in the classic version

**Comment by MatchGames** [comment]
**SOLVED; CLOSED**
