### ISSUE TITLE
[BUG] Placing more than 32 characters on a book author will make the book not show its content.

### ISSUE THREAD

**Issue by Luncaaa** [rockyhawk64/CommandPanels#110]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes, there isn't

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes, I was told I could make a new bug issue

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
If you put more than 32 characters in the author section in book= <author>, including color codes (&a &l...), if you open book it will say * invalid book tag *

### To Reproduce
1. In 'custom-item:' create any item with any name.
2. In material, type book= <author> (material: book= <any author>
3. Author must have +32 characters so this bug works. It can include color codes. Example: &a&lT&c&lE&a&lS&c&lT&a&lT&c&lE&a&lS
4. Save, get the book (with commands give-item: <custom item name> anywhere), open it and see *invalid book tag*

### Expected behavior
Author will show correctly even if it has more than 32 characters but I expected that when opening the book it would show the message I wrote in 'write:' section.

### Screenshots/videos
Nope, sorry.

### Versions:
 - Minecraft: 1.16.5
 - CommandPanels: 3.15.3.1 (latest)
 - Version I was using: 1.16.5
 - Server software: Paper #562

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.
I don't think it's a Minecraft thing because with other plugin I edited a book's author and placed +32 characters including color codes and it worked fine. There are no errors in console when saving file, reloading plugin or opening book.

I hope this can be fixed :)
~Luca

**Comment by rockyhawk64** [comment]
If you want to give a player a custom book instead of displaying it in the GUI I would suggest using the Minecraft built-in give command, there is a command creator here: [https://minecraft.tools/en/book.php](https://minecraft.tools/en/book.php)
