### ISSUE TITLE
InventoryOpenEvent cancel event issue

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#111]
### Describe the bug
Items drop from inventory when InventoryOpenEvent is triggered.

### To Reproduce
1. Cancel InventoryOpenEvent when a panel is opened.

### Expected behavior
Items that were in the GUI will drop to the ground.

### Versions:
 - Minecraft: N/A
 - CommandPanels: 3.15.3.1

**Comment by molocodev** [comment]
Any updates on this? It makes user experience bad for my user and due to it I can't add the plugin on my survival server.
