### ISSUE TITLE
Add PersistentDataContainer support

### ISSUE THREAD

**Issue by radqnico** [rockyhawk64/CommandPanels#113]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
Command Panels removes other plugin's tags from items.

### To Reproduce
1. Set a custom tag on a item using the PersistentDataContainer in a plugin
2. Put that item in a command panel
3. Save
4. Remove the item
5. Puf, tag is disappeared

### Expected behavior
Not to touch other plugins' custom tags

### Screenshots/videos
[Before putting it in a command panel](https://media.discordapp.net/attachments/824705163184963614/824706200800329799/unknown.png)

[After putting it in a command panel and taken out](https://media.discordapp.net/attachments/824705163184963614/824706375850393650/unknown.png)

### Versions:
 - Minecraft: 1.16.5

### Additional context/Panel files
Just put the item in the template panel

**Comment by radqnico** [comment]
Sorry, i didn't noticed I put a completely wrong title. My Falut.

**Comment by rockyhawk64** [comment]
CommandPanels doesn't use the same ItemStack it has its own system to add NBT, it uses PersistentDataContainer for its own items in the panels, other plugins shouldn't interfere with those items without direct plugin support. (dependencies)
