### ISSUE TITLE
No open GUI by using CP-Hotbar-Item

### ISSUE THREAD

**Issue by ErythroCraft** [rockyhawk64/CommandPanels#115]
Hi,

The issue is simple and an future request.

I've created an hotbar item to open the main menu on my server.
The main-GUI will open evvery time, but open the GUI by right-click on clickable blocks, too.

So, the issue is to have an update, that CP must testing the block if it clickable or interactable.

For an example, how to use every block testing all blocks fast by using hotbar items you can show

https://www.spigotmc.org/threads/how-do-i-check-if-a-block-has-a-right-click-behavior.394002/
and
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#isInteractable--

**Comment by rockyhawk64** [comment]
CommandPanel blocks are designed to be stationary blocks that don't change. So if you break the block it will not stay with the block. They are considered to be locations in a way as if you place another block in that location it will open the GUI.

I would suggest using a different plugin and assigning the command to open a GUI with that plugin.
