### ISSUE TITLE
Item-paywall not working 100% correctly on 1.8

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#117]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
**Yes**/No

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
**Yes**/No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
**Yes**/No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
**Yes**/No

### Describe the bug
When you have the exact amount of items specified in the item-paywall, the commands under the paywall will be executed, but the items won't be taken. If you have more/less it will work just fine.

### To Reproduce
1. Create an item with an item-paywall
2. have the exact amount of items (not one or more less/more)
3. See that the items aren't taken but the commands are being executed
### Expected behavior
If the item in the inventory has the same stack amount as the required amount in the paywall, the item will not be taken, yet the payment will be accepted.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: 1.8.9 (paperspigot)
 - CommandPanels: 3.15.4.0

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by rockyhawk64** [comment]
Closing until issue can be sourced
