### ISSUE TITLE
Open panels on player join

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#120]
### Describe the solution you'd like
Open a specific panel when a player joins the server. (or enters a specific world)

**Comment by TinyTank800** [comment]
Maybe add an option to only show it for new players and an option for always. Could use data for this somehow?

**Comment by RikkeBobbie007** [comment]
Howdy, Scrubbing through some wiki pages and trying to make a first time join panel. I'm curious how would I make it to where when a player joins it picks them up and opens a panel for them.
I can get panels to pull the data and i can backwards math some movement checks to allow for resource pack application
