### ISSUE TITLE
Item-paywall not work with custom name

### ISSUE THREAD

**Issue by Poulpinounette** [rockyhawk64/CommandPanels#123]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
Just not work.

### To Reproduce
https://pastebin.com/B6WuCPH1
and just try to trade the first item
i can remove iron_ingot not named.

### Expected behavior
Remove item named "l'ingot de fer" 

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: paper 1.16.5
 - CommandPanels: 3.15.4.0

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by TheLonelyWolf1** [comment]
Hello Poulpinounette,

Please revisit the Wiki and read through it again as it is probably no bug but rather a misconfiguration on your part.

the **"item-paywall="**-Tag can be either used as:
 **"item-paywall= [item] [amount]"** to use vanilla items as currency 
 _Wiki-Info: https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/executing-commands/panel-tags_
 or
 **"item-paywall= [custom item name]"** to use the custom items defined by the panelconfig
 _Wiki-Info: https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items_
 
 
Greetings,

TheLonelyWolf

**Comment by Poulpinounette** [comment]
Hi, already try. 
i use a basic iron ingot named "l'ingot de fer" (french transltation) and it doesn't work

**Comment by fireFerry** [comment]
Hi,
Item-paywall is based on the material, not the name. For example if you wanted to give the player a netherite sword if they give a diamond one, it should look like this:
```yaml
commands:
- 'item-paywall= DIAMOND_SWORD 1'
- 'minecraft:give %cp-player-name% minecraft:netherite_sword'
```

**Comment by Poulpinounette** [comment]
ok, it works when I add `"` at the beginning and at the end.

Thanks.
