### ISSUE TITLE
dropItem not working as intended

### ISSUE THREAD

**Issue by sxphirus** [rockyhawk64/CommandPanels#124]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
dropItem item tag not working as intended, items are deleted after picking them up

### To Reproduce
1. Create panel using 
      '2':
        material: AIR
        itemType:
        - placeable
        - dropItem
        hasvalue:
          material: AIR
          compare: '%cp-material-2%'
          value: DIAMOND_BLOCK
          output: false
          itemType:
          - placeable
          - dropItem
        hasvalue0:
          compare: '%cp-material-2%'
          value: DIAMOND_BLOCK
          output: true
          material: DIAMOND_BLOCK
          itemType:
          - dropItem
          stack: '%cp-stack-2%'
          commands:
          - console= eco give %cp-player-name% %cp-stack-2%'
          - setitem= example1 2
          - refresh
          - open= panel-30`
2. Move items around in inventory, place one into a dropItem slot
3. Item drops to ground, upon picking item up it disappears

### Expected behavior
Item drops to ground and does not disappear when in inventory

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
https://cdn.discordapp.com/attachments/749407995036696656/840172322803417088/glitch_w_cp.gif

### Versions:
 - Minecraft: 1.16.5
 - CommandPanels: Latest as per post (3.15.5.1)

https://0bin.net/paste/waZxd5SN#JLmCzKVFGM681AGKdGsk0bw94-Tc7DdXP4TVXFft/0B

**Comment by rockyhawk64** [comment]
If you want items that are generated in the GUI itself to drop you need to ensure the `noNBT` item type is also added to the item. Once that has been done the items will not disappear.
