### ISSUE TITLE
Adding in "unbreaking: true/false" for custom models under Durability

### ISSUE THREAD

**Issue by mrboog12** [rockyhawk64/CommandPanels#125]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes (No, he hasn't)

### Is your feature request related to a problem? Please describe.
Yes - Issue #106

### Describe the solution you'd like
Being able to add in unbreakable to custom items when using the "Damage: x"

Example: Golden Shovel with 18 durability shows a waffle, add "unbreaking: true" will display the waffle still but without the ugly yellow damage bar (cause cannot use Damage: 16 and then Damage: -1 as this would negate the whole thing rendering useless

### Additional context
Just necromancing something that was added that seems like it was rushed into an update? As #106 seems like it was closed and neglected to get any responses after the ticket issuer send comment after closure of ticket.

**Comment by fireFerry** [comment]
Hi,

If no further response to an issue is given, it's not being changed. There was an option added to use the unbreakable flag, and that's why the issue was closed. To use custom item textures you should really use custom model data instead of the durability of an item, it's much more simple and keeps things clean.

Cheers,
fireFerry

**Comment by mrboog12** [comment]
Can’t use custom model data pre 1.14

**Comment by fireFerry** [comment]
Hmm why aren't you using 1.14+? Can't really think of a big reason

**Comment by mrboog12** [comment]
Besides all the code changes, performance, etc.   take your pick

**Comment by fireFerry** [comment]
What is your current mc version?

**Comment by rockyhawk64** [comment]
custom model data will only be prioritized for 1.14+
