### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by dinobossytnew** [rockyhawk64/CommandPanels#128]
I wanted to ask you if you could add a function to migrate menu data from other plugins like deluxemenus, trmenus.

this includes its functions, actions do not have to be perfect maybe you can put some but not all since they are different depending on the plugin.

**Comment by TinyTank800** [comment]
Looking at trmenus idk if i could do those but i may be able to make an external program to move SOME stuff from deluxe menus into command panels. **I dont know if rocky the command panels dev will be intergrating anything like this into it but if he wants to he will reply here probably** but when i can ill see if i can create a quick program to transfer most stuff to each thing. again im not the dev just a mod who may be able to do something like it just to have it there.
