### ISSUE TITLE
Placeholders inside of data placeholders

### ISSUE THREAD

**Issue by carreb** [rockyhawk64/CommandPanels#129]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
I'd like to be able to use panel or even placeholderapi placeholders inside of panel data placeholders.
For example: %cp-data-dataName,{cp-selected-player}%

**Comment by rockyhawk64** [comment]
It Will be released in the next update (after v3.15.7.1).
