### ISSUE TITLE
Unable to move clickable item within inventory.

### ISSUE THREAD

**Issue by MartynBlackburn** [rockyhawk64/CommandPanels#13]
**Describe the Issue**
I am unable to move the clickable item around the inventory. When long-clicked the item immediately opens the menu instead of displaying that the item is about to be moved from the inventory slot. Additionally setting 'stationary: false' enables the item to be moved, but renders the item no longer clickable.

**Expected behavior**
A long-click on the item should move the item regardless of whether it opens the menu or not.

**Screenshots**
https://imgur.com/a/mWvp9fs
![2020-07-07_19 50 13](https://user-images.githubusercontent.com/26928665/86830367-84411180-c08d-11ea-820f-70cff0bfe824.png)

**Versions:**
 - Minecraft:  1.15.2
 - CommandPanels: 3.2.1

**Additional context**
https://pastebin.com/bDbTKHfA

**Comment by fireFerry** [comment]
What do you mean by long clicking?

**Comment by fireFerry** [comment]
Hi, after reading your issue again and Wolf explaining me the issue, I understand the issue you are having. This was a bug there has been since 3.1 and I thought it was already fixed. Update will be as soon as possible and status will probably seeable in Projects.

**Comment by rockyhawk64** [comment]
Have you tried to remove the stationary: 8 from the panel file? That will make clickable items movable.

**Comment by MartynBlackburn** [comment]
I removed 'stationary:8' from the file and it worked! Thank you.

**Comment by rockyhawk64** [comment]
Cool, the number stationary can be is from 0-8 and so I am assuming the item was stuck on the right side of your Hotbar since it was set to be locked there.
I will be closing this 👍
