### ISSUE TITLE
Open panel for another player using previous placeholder data

### ISSUE THREAD

**Issue by SebastianLeytonM** [rockyhawk64/CommandPanels#131]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem? Please describe.
There are no issues related to this feature request.

### Describe the solution you'd like
Think about singing a contract between two players and saving that data to placeholder data to be shown in a panel. Then one player must send a panel to the other, then go back with a response and data have to be stored for both.

### Describe alternatives you've considered
Simply using a book that one player writes and the other signs, but then there wouldn't be any data in any panel to be shown, let's say, about a rent or custom non-command job in a RPG gamemode.

**Comment by rockyhawk64** [comment]
Can be done using data sending data to the next player and the next player checking their data for panel information.
