### ISSUE TITLE
New RGB/HEX format

### ISSUE THREAD

**Issue by CroaBeast** [rockyhawk64/CommandPanels#132]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
There are no issues related to this feature request.

### Describe the solution you'd like
I want compatibility with this HEX color format: {#FFFFFF}.
They suggest me to add a pastebin of the code of one of the plugin that I use to see how it 'use' that HEX format.

### Describe alternatives you've considered
Idk about that one. Also I like cupcakes.

### Additional context 
Pastebin of the code of the HEX format: https://paste.helpch.at/odupomotos.nginx
Pastebin of the hole Main Class of the plugin: https://paste.helpch.at/omuboxomas.java
`Note: That plugin is a personal fork of the original plugin "RawMsg", because originally it uses the #<FFFFFF> format, so a dev told me how to replace that format to the one I'm requesting.`

**Comment by rockyhawk64** [comment]
https://github.com/rockyhawk64/CommandPanels/releases/tag/3.15.6.0
