### ISSUE TITLE
Check item's name with hasvalue

### ISSUE THREAD

**Issue by xRugHere** [rockyhawk64/CommandPanels#133]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
It isn't really an issue or a great ordeal, I just believe this feature would give players a lot more freedom when comparing values. Especially when making custom crafting and possibly grant other features.

### Describe the solution you'd like
I'm going to put this in context to make it easy to understand. I'm attempting to make a custom crafting GUI where the player can put an item in a slot and it will result in a different item in anther slot using has value. The problem is that there are multitude of items I'm using that are the same MATERIAL but different names. There's no way to differentiate "Example1Item" from "Example2Item", because they're both the same material. The only way to compare items in CommandPanels
 is %cp-material-#%, from what I've seen and heard from discord. I attached an image for what I think could be the solution if at all possible. The example shows that the hasvalue: and hasvalue0: on slot 15 are checking the 10th slot for items that are named "PotatoExample1" and "PotatoExample2". It would first check slot 10 for the item named "PotatoExample1", and obviously since the hasvalue: is checking for an item named PotatoExample1, the name and lore from hasvalue will be present in slot 15. As you can also guess, hasvalue0: would then check slot 10 for an item named "PotatoExample2", and give the name and lore given with hasvalue0:

### Describe alternatives you've considered
I've considered placeholderAPI being reliable but all I found were that the placeholders checked the players inventory instead of checking the slots of the GUI.

### Additional context
![Screenshot 2021-06-12 164224](https://user-images.githubusercontent.com/85808400/121789658-41d95c00-cb9d-11eb-9919-ad0f78606b0c.png)

**Comment by rockyhawk64** [comment]
I would recommend making a custom item in your panel, and then using the placeholder 
 %cp-identical-<custom item>,<slot>%
This way you can compare exactly what item is in a slot with whatever item you make as a custom item in the panel.

**Comment by rockyhawk64** [comment]
You can use NBT to do this instead which will work better too, closing.
