### ISSUE TITLE
1.17 - "Item-paywall" custom-item invalid detection payment amount

### ISSUE THREAD

**Issue by pa6324641** [rockyhawk64/CommandPanels#135]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
Use Item-paywall= custom-item ,Did not Deduct & Checking the correct amount.
But Use Item-paywall= minecraft:id stack ,Pay the correct amount.

### Expected behavior
Use Item-paywall= custom-item ,Pay the correct amount.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
[Youtube Videos](https://youtu.be/OCHYmW66eNc)

### Versions:
 - Minecraft: [1.17]
 - CommandPanels: [3.15.6.2]

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

[pastebin](https://pastebin.com/HTB3psNx)

**Comment by rockyhawk64** [comment]
Tested working in v3.15.7.1
