### ISSUE TITLE
Feature Suggestion: panelType: - returnItem

### ISSUE THREAD

**Issue by uwuxArbo** [rockyhawk64/CommandPanels#138]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
**Yes**/No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
**Yes**/No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
**Yes**/No

### Is your feature request related to a problem? Please describe.

It's sort of a problem, the config has a drop item setting where if the player closes the panel they drop the item, but I have npcs that open the panel and multiple people crowding around the npcs, so when someone closes their panel by accident. Their chances of getting that item are very low as some other players would most likely pick it up. So I'd like for there to be a setting in panelType in the panel itself for - returnInv which returns the item straight to their inventory.

### Describe the solution you'd like

Add a panelType with - returnInv which returns the item to the players inv instead of dropping it on the ground.

### Describe alternatives you've considered

Using worldguard to stop players from dropping items, but then some other stuff that requires the player to drop an item gets broken.

### Additional context

Nah I think I explained it well enough :)

**Comment by rockyhawk64** [comment]
- Add to ItemFallManager (Check Current Features for status on feature)
