### ISSUE TITLE
Feature Suggestion: panelType: - clickRefresh

### ISSUE THREAD

**Issue by uwuxArbo** [rockyhawk64/CommandPanels#139]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
**Yes**/No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
**Yes**/No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
**Yes**/No

### Is your feature request related to a problem? Please describe.

Refresh can cause _some_ server lag because it's constantly refreshing every 1 second just to keep the panel up to date with the player, so maybe instead the panel should refresh when the player clicks something, like if they click a black stained glass it does the clear and replace. So instead of refreshing every few seconds it only refreshes when a player clicks anything in the gui.

### Describe the solution you'd like

The panel should refresh when the player clicks something, like if they click a black stained glass it does the clear and replace. So instead of refreshing every few seconds it only refreshes when a player clicks anything in the gui.

### Describe alternatives you've considered

I haven't really considered alternatives.

### Additional context

Nah

**Comment by rockyhawk64** [comment]
If you add the command 'refresh' to an item when it is clicked it will refresh the panel, even if the refresher is disabled.
