### ISSUE TITLE
Improved Input System

### ISSUE THREAD

**Issue by Maroon28** [rockyhawk64/CommandPanels#142]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes, it was closed with #issue 126, with no comments. 

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
With the current input system, the plugin runs any commands AFTER the input, even if the input is still not given. For example, this

### Describe the solution you'd like
Put ALL the commands after an input request on hold, until an input is provided, then proceed to run the commands.

### Describe alternatives you've considered
I've attempted to put a delay for the commands, but it's way too inefficient, since you can't predict how fast the user will type the input.

### Additional context
N/A

**Comment by rockyhawk64** [comment]
It won't be done for a while I will re-open the ticket if it is done in the future. The current system cannot be improved and would need to be redone for that to happen. (if multiple commands have the placeholder they will all run after the input is entered).

I would recommend using placeholders to open the panel, like /example RockyHawk and then assigning the argument to a placeholder in the panel.

https://github.com/rockyhawk64/CommandPanels/issues/126

**Comment by rockyhawk64** [comment]
Will be using a separate system that is in development
