### ISSUE TITLE
MMO Items Not Working

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#143]
Will be fixing when MMO Items updates to 1.17

### Versions:
 - Minecraft: Idk probably most

**Comment by ErythroCraft** [comment]
MMO Items is Prime
https://www.spigotmc.org/resources/mmoitems-premium.39267/

1.17 is updated

**Comment by rockyhawk64** [comment]
No issues related to MMO Items being created in GUIs and selling MMO items as custom items
