### ISSUE TITLE
Could not pass event InventoryClickEvent to CommandPanels

### ISSUE THREAD

**Issue by ErythroCraft** [rockyhawk64/CommandPanels#146]
Hi @rockyhawk64 

I installed the latest version of your plugin and found a bug by using items in GUI.

**CraftBukkit version 3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)**

**CommandPanels v3.16.2.4**

**Reproduce** by left or right click items in GUI to open other GUIs with 
   /commandpanels [panel]

--
Caused by: org.bukkit.command.CommandException: 
Unhandled exception executing 'commandpanel' in 
org.bukkit.command.FormattedCommandAlias(commandpanel)
--
Caused by: java.lang.StackOverflowError
--

https://pastebin.com/GhY7BqCD

**Comment by TinyTank800** [comment]
You should use 
Commands:
- open= panelname

**Comment by TinyTank800** [comment]
Of course github formats it weird. On the wiki find command tags and use the open= panelname format

**Comment by ErythroCraft** [comment]
Thanks a lot.
