### ISSUE TITLE
hex codes don't work in panels using msg=

### ISSUE THREAD

**Issue by kaciecat** [rockyhawk64/CommandPanels#152]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
using hex codes works in the tag but not in a panel using msg=

### To Reproduce
1. create a panel
2. add an item with the command msg=
3. add a hex code using the "#000000" format
4. save and restart server or reload plugin
5. bring up the command using /cp (panel name)

### Expected behavior
hex codes should not show up as the code in chat, instead showing up as the color as it does in version 3.15.5.5

### Screenshots/videos
![bug1](https://user-images.githubusercontent.com/82332439/126917070-3fe18dea-85c7-4847-8d9c-531c0fefb76d.png)
![bug2](https://user-images.githubusercontent.com/82332439/126917071-2765ac8a-2a67-44af-8396-fe16dc4e3df7.png)
![bug3](https://user-images.githubusercontent.com/82332439/126917094-c4144834-a976-40c5-9b9d-6af579f6de49.PNG)
![bug4](https://user-images.githubusercontent.com/82332439/126917107-b22c5c12-bd2e-4344-85cc-d17243b5db34.png)

### Versions:
 - Minecraft: 1.17.1
 - CommandPanels: 3.16.2.4

### Additional context/Panel files
https://pastebin.com/mmC2yZnb

**Comment by rockyhawk64** [comment]
Fixed 3.16.2.5
