### ISSUE TITLE
Add PlaceholderAPI support for data placeholders

### ISSUE THREAD

**Issue by Maroon28** [rockyhawk64/CommandPanels#155]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
No. 

### Describe the solution you'd like
A way to display/use some CP placeholders outside of panels. I.E add placeholderapi support to them. Obviously, stuff that doesn't make sense outside of panels shouldn't be included, such as %cp-player-name% or %cp-material% etc. However, stuff like data values would be _really_ handy to have outside of just panels. 

### Describe alternatives you've considered
None, there aren't really any other ways to do this.

**Comment by rockyhawk64** [comment]
Will create a link so current placeholders can be accessed using PlaceholderAPI
