### ISSUE TITLE
enable to use accents and symbols (UTF-8)

### ISSUE THREAD

**Issue by Delgado-tech** [rockyhawk64/CommandPanels#157]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
The plugin don't have support for word like: á ã õ à í, when your use accents the name or lore of the item bugs, the same occurs when you use symbols, have other plugins with this feature.

### Describe the solution you'd like
I wanted you add this feature, because open more doors for you, because have other languages use this accents, and this is super helpful for translate language. And symbols because make the visual more better. I think this is possible using UTF8 for encoding string variable.

### Additional context
This example is written in lore: - 'Total de vitórias' 
![image](https://user-images.githubusercontent.com/60985347/129444815-c787520e-2193-4d2c-9b69-472612f7195a.png)

**Comment by fireFerry** [comment]
You should be able to save your panel itself with the right encoding, for example with Notepad++:
![afbeelding](https://user-images.githubusercontent.com/61279925/129445191-2effa09c-a381-4bb2-911f-2aaa4373da76.png)

**Comment by Delgado-tech** [comment]
> You should be able to save your panel itself with the right encoding, for example with Notepad++:
> ![afbeelding](https://user-images.githubusercontent.com/61279925/129445191-2effa09c-a381-4bb2-911f-2aaa4373da76.png)

I use UTF-8 for saving files, the character don't bug in file, bug in java compilation I supose.
For compile utf8, example:
```
String rawString = "ã~íñ";
ByteBuffer buffer = StandardCharsets.UTF_8.encode(rawString); 

String utf8EncodedString = StandardCharsets.UTF_8.decode(buffer).toString();

assertEquals(rawString, utf8EncodedString);
```

**Comment by Delgado-tech** [comment]
Your codification is in Unicode, I find one way for bypass this, is using the respective value in the table of unicode (https://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=128&names=-&utf8=string-literal), but this for a normal user this is not practical, but is good in future change unicode to utf8 encoding.

**Comment by rockyhawk64** [comment]
The plugin is designed for Java 16, any other versions of java are no longer tested and supported. I have tested and confirmed the character works when I use Java 16 on Minecraft 1.17.
