### ISSUE TITLE
Animation bug when you put material equals of the others frames of animation (animete0,1,2...)

### ISSUE THREAD

**Issue by Delgado-tech** [rockyhawk64/CommandPanels#158]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
I don't understand why this is occurs, but when you create a animation, if you put the material of the frame zero the same of the frame one you can see a dalay of this animation

### To Reproduce
1. Create a panel in panels folder with animateValue
2. Create one animation for one item
3. Put Material value the same of the animate0, animate1, etc...
4. Change the name of the itens for see change difference
5. In minecraft server open the panel and see the velocity of change
6. Back on file of the created panel and change the material value for a different value of other animete0, animte1, etc...
7. Back in minecraft and reload config file (/cpr), and open panel, and you see the difference of velocity.

### Expected behavior
I wanted the animation don't have this delay if the item is the same, because somethimes you only need animate the lore and not the item material.

### Screenshots/videos
You can see the diffence in this gif, I only change the material value:
If applicable, add screenshots or videos to help explain your problem.
![bug](https://user-images.githubusercontent.com/60985347/129445154-ab11e12d-bdc7-48c4-9ef6-9c696af0c8c8.gif)

### Versions:
 - Minecraft: [e.g. 1.8.8]
 - CommandPanels: [e.g. 3.16.3.1]

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by fireFerry** [comment]
For `material:` you should use the material name, not the id.

**Comment by Delgado-tech** [comment]
> For `material:` you should use the material name, not the id.

Don't have difference, I change for the name and continues equals of the gif bug

**Comment by fireFerry** [comment]
What is your refresh delay set to?

**Comment by Delgado-tech** [comment]
> What is your refresh delay set to?

refresh-delay: 2
The refresh delay works fine if itens are different than others, but if the itens is the same, the daley is more bigger or ignore refresh-delay

**Comment by fireFerry** [comment]
The refresh delay is in ticks, so 2 ticks would be really fast.

**Comment by Delgado-tech** [comment]
> The refresh delay is in ticks, so 2 ticks would be really fast.

Yes, look the gif i posted in first comment

**Comment by rockyhawk64** [comment]
This has been confirmed to be an issue, however, it is a Minecraft legacy version bug (1.12 and below) so there will be no plans to fix it at this time.
