### ISSUE TITLE
Plugin taking up a lot of tick on 1.16

### ISSUE THREAD

**Issue by DrakePork** [rockyhawk64/CommandPanels#16]
**Describe the bug**
After checking out 1.16 I noticed that CommandPanels is now suddenly using a lot more tick than it used to, and I mean a lot more.

**To Reproduce**
Run the newest verison of commandpanels on a 1.16 server.

**Expected behavior**
To not take up extreme amounts of tick.

**Screenshots**
[Timings](https://timings.aikar.co/?id=911949f716054873b48736a24f36105e#plugins)

**Versions:**
 - Minecraft: 1.16.1 Paper
 - CommandPanels: 3.2.3

**Comment by rockyhawk64** [comment]
Try following these steps: https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by DrakePork** [comment]
Nupe CommandPanels still taking up a lot of tick, especially through PlayerInteractEvent
https://timings.aikar.co/?id=d5ef3568b5a04230af1a2da08679224d#plugins

**Comment by rockyhawk64** [comment]
Can you send your CommandPanels plugin folder? I have had no issues with paper using 1.16 to this extent, usually, there is some external factor or something in the plugins folder that causes this.

**Comment by DrakePork** [comment]
[Plugin List](https://i.imgur.com/47vYOaK.png)

[CommandPanels Folder](https://www.dropbox.com/s/os1p1b2cxgl9md5/CommandPanels.zip?dl=0)

**Comment by fireFerry** [comment]
Just a quick note, Command Panels is **not** compatible with Plugman, you need to use /cpr or restart your server.

**Comment by DrakePork** [comment]
Yeah, I only use plugman restart on my custom coded plugins.

**Comment by rockyhawk64** [comment]
https://www.spigotmc.org/threads/too-many-plugins-is-bad.904/
Should have a read of this, CommandPanels could be lagging as a result of this.

**Comment by DrakePork** [comment]
Well I've investigated some more and its 100% CommandPanels as I tested it with only this plugin, but appears to be happening due to one of my panels so I'll see if I can find out which one it is and why its causing PlayerInteractEvent to go crazy.

**Comment by DrakePork** [comment]
Well I've tracked it down to these two files [Files](https://www.dropbox.com/sh/ql10wg2p46z4dlz/AAD16GZmgxBUhdqrgdMB88h4a?dl=0)

Dont really know why they're causing PlayerInteractEvent to go crazy but yeah.

**Comment by DrakePork** [comment]
The other problem is that those two panels up there are not released/rarely used and when I was testing earlier with only CommandPanels I was literally just having all the panels on and then flying around and breaking blocks which caused the PlayerInteractEvent to happen.

**Comment by rockyhawk64** [comment]
Yeah, the PlayerInteractEvent is called when the player interacts, aka right-clicking blocks for an example.

This is the code for the event here too: https://github.com/rockyhawk64/CommandPanels/blob/665bc5cb75295c8cfa032e8ba2eb7f161ff99ca6/src/me/rockyhawk/commandPanels/utils.java#L283
Which shows it isn't that long.. (line 283-322)

Either way, I will add some updates that will disable code that isn't required, as that code for you would not be required because it is only to open the panel via Hotbar.

**Comment by rockyhawk64** [comment]
I have added some optimization for future updates. The PlayerInteractEvent that seems to be lagging will not run if it doesn't need to (which is didn't in your case).
There seems to still be higher timing, despite it only running almost nothing. Very strange, not sure why it would be spitting that out, either way, it will run better.

**Comment by DrakePork** [comment]
What I meant by long was those panel files being 1000+ lines long, not the event, but yeah that latest update seems to have fixed it. Thanks.
