### ISSUE TITLE
Intigration of Geyser and Flootgate

### ISSUE THREAD

**Issue by ErythroCraft** [rockyhawk64/CommandPanels#168]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No it's new

### Is your feature request related to a problem? Please describe.
I'm using the [Geyser](https://github.com/GeyserMC/Geyser) and [flootgate](https://github.com/GeyserMC/Floodgate) plugin.
They have craeted the [global_api](https://github.com/GeyserMC/global_api).
With this plugin bedrock user can join and play my java server.

The problem is to see the custom heads I created in the Guis looks very bad.
Next I post any pictures to understand the problem.

### Describe the solution you'd like
I don't know how you can fix this.

### Describe alternatives you've considered
There are no futures in the www. It's new and you are the first person I ask.

### Additional context
1. **Picture after joining the server with my java account**
![main_menu](https://user-images.githubusercontent.com/76217862/135900512-1b2657d3-8397-47a6-8906-935b0d9141ae.png)

![setting_menu](https://user-images.githubusercontent.com/76217862/135900525-ef21a9f0-54f4-44a5-97b5-38b32a924479.png)

2. **Picture after joining the server with my bedrock account**

![main_menu_bedrock](https://user-images.githubusercontent.com/76217862/135900648-9bdd6cbc-9a30-4fd7-9f9e-7c488be10d3e.png)

![setting_menu_bedrock](https://user-images.githubusercontent.com/76217862/135900688-5d708606-7f21-49e7-887b-0e5de9d631bd.png)

**Comment by rockyhawk64** [comment]
This has nothing to do with CommandPanels. Please refer to this GitHub issue [https://github.com/GeyserMC/Geyser/pull/683](https://github.com/GeyserMC/Geyser/pull/683)
