### ISSUE TITLE
Make player inventory wipe during the use of bottom/middle panel client-side

### ISSUE THREAD

**Issue by SeaSon2002** [rockyhawk64/CommandPanels#174]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
if i choose to use middle/bottom panel, player inventory will get wiped temporary ( including armors, right+left hand item like shield, totem). This renders player vulnerable to monsters and all other damge sources since they will have no protection while the panel is open.

### Describe the solution you'd like
Player inventory should not be wiped server-side. Do it only for client-side

### Describe alternatives you've considered
Making player invincible while panel is being used.  Players will most likely abuse it (for example open the panel during combat/explosion)

**Comment by SeaSon2002** [comment]
Btw the way the plugin handle inventory makes new items doesnt get saved if player pick up them from the ground during mid/bot panel use

**Comment by rockyhawk64** [comment]
To avoid this I would suggest not using the bottom two halves of the inventory. There are no client-side/server-side item differences that I am aware of.
However, since armour does not affect the items in the inventory a fix will be added that will not remove armour from the player while the panels are open.

**Comment by SeaSon2002** [comment]
maybe you can take a look at trmenu, they managed to achive that
https://github.com/TrMenu/TrMenu

**Comment by SeaSon2002** [comment]
but anyway thanks for the update, having the armor kept is definitely better

**Comment by rockyhawk64** [comment]
This will be kept open
