### ISSUE TITLE
Add Support for a plugin called "Skulls"

### ISSUE THREAD

**Issue by KahpotVanilla** [rockyhawk64/CommandPanels#176]
All the details about the Plugin and the link: https://www.spigotmc.org/resources/skulls-the-ultimate-head-database.90098/

**Comment by fireFerry** [comment]
This will not be added, as CP already supports all heads from [https://minecraft-heads.com/custom-heads](https://minecraft-heads.com/custom-heads). Please read the [wiki section](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#material) on how to do so.
