### ISSUE TITLE
Add FakeSender for commandtags

### ISSUE THREAD

**Issue by K0bus** [rockyhawk64/CommandPanels#179]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
When use console sender on command tag, command output will be send in main server console.
I will have to make a FakeSender allow to send command by Console without any prompt in the Server Console.

### Describe the solution you'd like
I create this FakeSender https://pastebin.com/Y5dFYMvA with this you can use it in your dispatchCommand and allow you to run command without any output.

**Comment by rockyhawk64** [comment]
This won't be added due to plugin conflicts, as it can cause issues with other plugins if a command is executed that actually requires a player instance. As the plugins will think there is a player instance it can cause issues.
