### ISSUE TITLE
Sequence problem command 

### ISSUE THREAD

**Issue by AzCreep** [rockyhawk64/CommandPanels#18]
**Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?**
Yes

**Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?**
Yes

**Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)?** *(Or got redirected to a Github issue here)*
Yes

**Describe the Issue**
Well i saw this example (https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/command-sequences) and when i try to do the same it doesn't let me use the item when i left click it

**Expected behavior**
To do exactly what shows on the images

**Screenshots/videos**
https://gyazo.com/c96d8ff72a5029a78b6946a8756eedb7
https://imgur.com/nUqd7LX

**Versions:**
 - Minecraft: 1.16.1
 - CommandPanels: 3.3.1

**Additional context/Panel files**
https://pastebin.com/KiPbd13G

**Comment by rockyhawk64** [comment]
The sequence has to be in the same file, so you aren't able to call for the admin panel inside of the ban panel.

**Comment by fireFerry** [comment]
The sequence you copied was panels.adminPanel.sendMessage, but your panel is named BanPanel. So replace it with panels.BanPanel.sendMessage and it should work!

**Comment by AzCreep** [comment]
OMG XD ye it worked can't believe it....sorry for the trouble and thanks for the help!
