### ISSUE TITLE
Players unable to open panel from chest (used /cpb add (panel) to let players open a panel from a block)

### ISSUE THREAD

**Issue by GreenArrowlol** [rockyhawk64/CommandPanels#181]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
Okay so when there's 0 ops, players are able to open the panel through the chest but when there's 1 op the other players are unable to open the chest

### To Reproduce
1. N/A

### Expected behavior
We should be able to open the panel by right clicking the block even when there's a op

### Screenshots/videos
https://www.youtube.com/watch?v=qz_yJEV4yfQ

### Versions:
 - Minecraft: [1.16.5]
 - CommandPanels: [3.17.2.0]

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by GreenArrowlol** [comment]
And also, as soon as the second player deoped, the first player was able to open the panel by right clicking the block

**Comment by rockyhawk64** [comment]
Can you send a paste of the panel and the other plugins you have, it sounds like a permissions issue. On my test server I am able to assign a panel to an Ender Chest and it works oped or deoped.

**Comment by GreenArrowlol** [comment]
I don't think you've understood the issue.
- when player 1 is oped and player 2 is deoped, player 2 is unable to open the chest whereas when both player 1 is deoped and player 2 is deoped then player 2 is able to open the chest

**Comment by jman13378** [comment]
> I don't think you've understood the issue.
> 
> * when player 1 is oped and player 2 is deoped, player 2 is unable to open the chest whereas when both player 1 is deoped and player 2 is deoped then player 2 is able to open the chest
> 
> theres no issue with permissions here
> 
> panel: https://www.toptal.com/developers/hastebin/atofenohow.yaml

Does the panel have any errors when you try

**Comment by GreenArrowlol** [comment]
I think it's a internal issue. Had no issue with the panel. The only thing the only thing the panel had was 3 items.

**Comment by rockyhawk64** [comment]
Cannot replicate issue + has never been brought up.
