### ISSUE TITLE
[Suggestion] Add command tag insert= 

### ISSUE THREAD

**Issue by Bibithom** [rockyhawk64/CommandPanels#182]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
not related

### Describe the solution you'd like
I would like be able to insert text in playertchat like vanilla does with json components.
When clicked, sentence behind "insert=" tag will apear in tchat and player has to hit enter to send it in tchat.

Vanilla commands can do that with json components, for example : /tellraw @s {"text":"Click me !","color":"red","clickEvent":{"action":"suggest_command","value":"/command to enter"}}.

### Describe alternatives you've considered
I've wondered about using minecraft's json system in commands, but, multiple characters like "{" or, "," or ";" or " " " will be really hard to escape/ keep clean / works

### Additional context
no additionnal context.

Have a good day, thank's in advance for your consideration.

**Comment by MangoSwirl** [comment]
I'm pretty sure that's only possible with a click event in JSON text components (ie books, chat) and the event is handled client side, so this wouldn't be possible.

**Comment by Bibithom** [comment]
Ok thank you for your answer have a good day
