### ISSUE TITLE
Hide multiple attributes

### ISSUE THREAD

**Issue by NoltoxGit** [rockyhawk64/CommandPanels#184]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
When I want to make a menu using leather armor, there is the color underneath the item that appears, and before using CommandPanels, I was using DeluxeMenus which had this capability.

### Describe the solution you'd like
A feasible solution would be to do what DeluxeMenus or BossShopPro do, i.e. add hiding attributes like [all those if.](https://cdn.discordapp.com/attachments/885539380998070272/922766057188515881/unknown.png)

**Comment by MangoSwirl** [comment]
From what I can tell, [hiding attributes](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#item-type) has already been added. Is it hiding only specific attributes (ie. Hiding the color but not the enchantments) that you want to see added?
