### ISSUE TITLE
/commandpanelclose and /cpc commands are missing?

### ISSUE THREAD

**Issue by RalphORama** [rockyhawk64/CommandPanels#187]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?

Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?

Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*

Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

Yes

### Describe the bug

The Command Panels wiki [states](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/faq#how-can-i-close-the-panel-when-someone-clicks-on-an-item)

> To close a panel using an item, you can add the command `commandpanelclose` or `cpc` for short, to the item's commands.

However, when I try to run these commands in-game, I get "command not found" errors.  I checked `plugin.yml` and the commands do not seem to be defined there either.

### To Reproduce

- Install Command Panels
- Option 1: Try the commands by hand
   1. Log into the server and run commands `/commandpanelclose` and `/cpc`
   2. Both return a "command not found" error
- Option 2: Create a test panel
   1. Create a test panel 
   2. Add an item to the panel
   3. Set up the `commands` field for the item to include `commandpanelclose` or `cpc`
   4. Open the panel and click the item
   5. Get a `command not found` error

### Expected behavior

The command exists and the panel closes.

### Versions:
 - Minecraft: Paper version `git-Paper-133 (MC: 1.18.1)`
 - CommandPanels: 3.17.2.2

### Additional context/Panel files

https://gist.github.com/RalphORama/ea965ebbc341f03799399e1a8be6b5dc

**Comment by rockyhawk64** [comment]
`commandpanelclose` is no longer used
https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/executing-commands/panel-tags
only `cpc` is used as seen in the wiki, it is also not a command you can do /cpc with, it is a command tag that only works in the panels itself

**Comment by RalphORama** [comment]
`cpc` works! Thank you for your help.
