### ISSUE TITLE
The material cannot be displayed normally.

### ISSUE THREAD

**Issue by 1536364007** [rockyhawk64/CommandPanels#189]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
A clear and concise description of what the problem is.

After I added the material of book and quill to a generated panel and saved the panel configuration file, when I open this panel in the game, the commandpanel plugin reports an error in the chat bar and does not display the material of book and quill in the panel.

### Expected behavior

Correctly display the materials of books and quill without error

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

![1](https://user-images.githubusercontent.com/61043370/151497276-ec81dbdf-7213-4fb2-894e-ea664c09502a.png)

![2](https://user-images.githubusercontent.com/61043370/151497279-1ca555f6-af2d-4d39-9916-5694661cc9e1.png)

![3](https://user-images.githubusercontent.com/61043370/151497297-0366b368-273e-4172-ad86-0c61b0bc089c.png)

![4](https://user-images.githubusercontent.com/61043370/151497307-b667b405-417c-4c71-86c2-bdef9c67c77c.png)

### Versions:
 - Minecraft: [1.16.5]
 - CommandPanels: [3.17.3.0]

### Additional context/Panel files
Add any other context about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

Here is the pastebin link:
https://pastebin.com/pgn2GiWr

By the way: Your CommandPanel plugin is an easy-to-use and highly operable plugin.It runs very well on my minecraft server.Everything else is good except this small problem
I am looking forward to your early reply. Thanks  :)

**Comment by fireFerry** [comment]
In this version of Minecraft, the Material name found in the [Spigot API](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html) for book and quill is `WRITABLE_BOOK`. If you change your material to: `material: WRITABLE_BOOK` it will fix the item.
