### ISSUE TITLE
Buying with money

### ISSUE THREAD

**Issue by Colem4n95** [rockyhawk64/CommandPanels#19]
How do i make things sell-able with vault im confused with how it works

**Comment by fireFerry** [comment]
You can do that using the sell= tag. More information explained

**Comment by Colem4n95** [comment]
ok sorry i miss typed what i meant i meant buy so im using this plugin called moarbows and want them, to be buy-able so would i do this?
-buycommand= 1000 moarbows get TRIPPPLE_BOW  %cp-player-name%

**Comment by fireFerry** [comment]
yes, but you need a space between the - and the b
