### ISSUE TITLE
Silent data commands

### ISSUE THREAD

**Issue by Maroon28** [rockyhawk64/CommandPanels#191]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
I use commandpanels data everywhere in my server since its so versatile and has a lot of uses, and it even hooks in with other plugins using placeholders. The only issue I have here is when doing a lot of data assignments simultaneously, the console gets spammed and clogged up quite a bit.  

### Describe the solution you'd like
There are a few things we could do. First being adding a 'silent' at the end of the command, or '-s'. So something like this for example:
`/cpdata set Maroon28 level 15 -s`, would set the level data to 15 and not send any messages back. We could also have a config option for it, but I think the command argument adds more flexibility 

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by rockyhawk64** [comment]
You can set data by parsing placeholders too which does this
https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/placeholders-and-panel-editing
If you want to do it through another plugin that hooks into PlaceholderAPI, you can also do something like this:
`%commandpanels_setdata-example,test1%`, just navigate to the External Placeholders area on that link

**Comment by Maroon28** [comment]
Oh, very cool, didn't know that! Unfortunately I don't think this alone would suffice what I'm trying to do. A lot of my uses are 'global' data. Meaning I set the data to a player that doesn't exist, and then I just use %commandpanels_data-test,fakeplayer%. It doesn't seem like you can add a player argument to the set data placeholder? I may be missing it though.
