### ISSUE TITLE
add an blacklist for items in sell and buy

### ISSUE THREAD

**Issue by AceNetAW** [rockyhawk64/CommandPanels#192]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the solution you'd like
I would like to wish an option, an gui, to set items on an blacklist that cant be sold.
directly described:
i has an shop with blaze rods and custom items (with lores, etc.) and the normally items (blaze_rod) is added in the shop to be sold.
but when i would like to sell the normal blaze_rods it will sell the the custom rods too.

Option 1: An ingame editor like "/cpa blacklist" should be open to open an gui there items can be added the didnt should be selled.
Option2: an command or config line to disable "lore" items, all items that has an nbt tag or lore should not be could selled

**Comment by TinyTank800** [comment]
Unsure on if recent paywall changes which allow the search of custom model data or no custom data help in this case.

Possible remedy is allow the requirement of specific name or no lore for item paywall and sell tags.

**Comment by TinyTank800** [comment]
This will be fixed in the next pull request made by me. A lot of item paywall changes come with it and the main one is normal paywalls do not take any item with custom meta data attached to them.
