### ISSUE TITLE
All items work for sale, except items from the mmoitems plugin

### ISSUE THREAD

**Issue by NeotenySS** [rockyhawk64/CommandPanels#193]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Got redirected to a Github
![image](https://user-images.githubusercontent.com/11386982/158439542-f139f3fe-a57b-42d8-9d5b-c9f27654e06d.png)

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
Any item can be sold or exchanged.
Except for the item from the mmoitems plugin.
I tried all options. I've checked all of Discord for help requests to make sure there's no solution.
Why is this a mistake?
Can items be sold? Yes

### To Reproduce
1. Create shop and paste this code (example shop1):
'0':
        material: mmo= MATERIAL TEST
        name: 'Test name'
        lore:
        - '&7Buy 1 R'
        - '&7Sell 1 R'
        commands:
        - "item-paywall= mmo= MATERIAL TEST"
2. Reload plugin.
3. open panel /cp shop1
4. try to sell
5. Error:
`https://pastebin.com/MqT0WTZG`

### Expected behavior
The ability to sell an item from the mmoitems plugin or exchange for another mmoitems item.
Since regular items or custom-item I can sell or exchange.

### Screenshots/videos
Sorry, not available.
Described above in detail.

### Versions:
 - Minecraft: 1.18.1
 - CommandPanels: 3.17.3.1

### Additional context/Panel files:
https://pastebin.com/MqT0WTZG

**Comment by NeotenySS** [comment]
As far as I know, the guys from TeamRequiem do not hide the code for injection into other plugins.
Here's a link to check the item and the up-to-date API.
https://git.mythiccraft.io/mythiccraft/mmoitems/-/wikis/Main%20API%20Features
https://git.mythiccraft.io/mythiccraft/mmoitems/-/wikis/Stat%20API

If there are difficulties, then I would recommend a tough guy nicknamed Gunging.
But the owner of Joshinn will be able to help in case of emergency.

**Comment by fireFerry** [comment]
You will need to create a custom panel item and use that in the item-paywall=

**Comment by rockyhawk64** [comment]
MMO Items work differently and need to be assigned through a custom item. This way the paywall will be able to identify the item correctly, this is how you would do it:
```YAML
panels:
  test:
    perm: default
    rows: 1
    title: '&8Test Panel'
    custom-item:
      example1:
        material: mmo= MATERIAL TEST
    item:
      '4':
        material: DIRT
        name: 'Sell the MMOItem'
        commands:
        - item-paywall= example1
```

**Comment by NeotenySS** [comment]
Plugin send message "No item"
Config work.
item:
    success: '&aItem Salled %cp-args%.'
    failure: '&cНNo item!'

My example:
   panels:
  test:
    perm: default
    rows: 1
    title: '&8Test Panel'
    custom-item:
      tradedd:
        material: mmo= ARMOR UNI_ETTASFFQWRR_ARM_POJ
    item:
      '4':
        material: mmo= ARMOR ARMOR UNI_ETTASFFQWRR_ARM_POJ
        name: 'Sell element mi'
        commands:
        - item-paywall= tradedd

But plugin dont see item

**Comment by rockyhawk64** [comment]
Can you paste in the panel file without the spacing being removed, at the moment all of the lines are on the very left.
Try setting the command to `give-item= tradedd` instead to see if the item is being created properly, if not can you send an error screenshot?
