### ISSUE TITLE
Accessing a panel item without permissions

### ISSUE THREAD

**Issue by GlobusOk** [rockyhawk64/CommandPanels#194]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes
### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
a player without permission gets the right to receive privileges to the command panel

### To Reproduce
When moving from world to end world
In the inventory, players have items for which there are no rights.
By default, gave the players commandpanel.panel.default,

### Expected behavior
I would like that items would not be issued to the inventory without permissions

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: [1,18,2]
 - CommandPanels: [last]

### Additional context/Panel files
panel/item 1 https://pastebin.com/6hpHQUQi
panel/item 2 https://pastebin.com/4H7u5Qde

**Comment by rockyhawk64** [comment]
THe pastebin links are not working. Can you make new ones?

**Comment by jonjon1322** [comment]
> ### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
> Yes
> 
> ### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
> Yes
> 
> ### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? _(Or got redirected to a Github issue here)_
> Yes
> 
> ### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
> No
> 
> ### Describe the bug
> a player without permission gets the right to receive privileges to the command panel
> 
> ### To Reproduce
> When moving from world to end world In the inventory, players have items for which there are no rights. By default, gave the players commandpanel.panel.default,
> 
> ### Expected behavior
> I would like that items would not be issued to the inventory without permissions
> 
> ### Screenshots/videos
> If applicable, add screenshots or videos to help explain your problem.
> 
> ### Versions:
> * Minecraft: [1,18,2]
> * CommandPanels: [last]
> 
> ### Additional context/Panel files
> panel/item 1 https://pastebin.com/6hpHQUQi panel/item 2 https://pastebin.com/4H7u5Qde

im pretty sure commandpanel.panel.default is automatically given with the default group within your perms manager if of course you have a perm manager
