### ISSUE TITLE
command tag "drop="

### ISSUE THREAD

**Issue by dani626** [rockyhawk64/CommandPanels#195]
**### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?**
Yes

**### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?**
Yes

**### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)***
Yes

**### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.**
My server has compatibility with minecraft bedrock with the plugin called geyser and this version of minecraft does not have the right click.

**### Describe the solution you'd like
A clear and concise description of what you want to happen.**
I need the player to execute a command when dropping an item just like right click works.
the line of code would be:
   - 'drop= msg= You have dropped an item!'

**### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.**
the only solution I have is to create 2 panels, one for left click and one for right click for bedrock version players.

**Comment by rockyhawk64** [comment]
You can find another plugin or get a custom plugin that executes a command to open a panel when items are dropped, however, this isn't going to be added to CommandPanels.
