### ISSUE TITLE
auto data loader

### ISSUE THREAD

**Issue by jman13378** [rockyhawk64/CommandPanels#197]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
YES if data lets say `playtimestreak` it will = to null so the panel will have an error 
### Describe the solution you'd like
so a true or false n\in the config for it so 

auto-data: <T/F>
data: <value>
 ### sets all data in all panels
   or

auto-data: <T/F>
-panelname: <value> ### sets all the data in the specific panel
so this will look through the panels and auto set all data thats in the panel so lets say a panel has 3 data values 
playtimer
playtimestreak
playtimestreaklast
on panel open it will auto set the datas included in the panel to the set data value in the config

### Describe alternatives you've considered
commands-on-open:
- add-data=

**Comment by rockyhawk64** [comment]
Sounds like you would want to use preload commands instead of commands on open
```YAML
pre-load-commands:
- add-data= test1 true
```
This will set a value before the panel opens, so once the panel actually starts to load the value will not be null.

**Comment by jonjon1322** [comment]
> Sounds like you would want to use preload commands instead of commands on open
> 
> ```yaml
> pre-load-commands:
> - add-data= test1 true
> ```
> 
> This will set a value before the panel opens, so once the panel actually starts to load the value will not be null.

yes that's what i meant
