### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by rodor03** [rockyhawk64/CommandPanels#20]
me.rockyhawk.commandPanels.panelBlocks.panelBlockOnClick.onInteract(panelBlockOnClick.java:28)

**Comment by TheLonelyWolf1** [comment]
Please give us more information of your problem.

- Plugin Version
- Server Software(Spigot, Paper, ...) + Version _Note: For Paper please give us your Build-Nr. too_
- Serverlog
- A better description of what happened

**Comment by rockyhawk64** [comment]
https://www.spigotmc.org/resources/command-panels-custom-guis.67788/

Version 3.4.2 should solve this issue.
