### ISSUE TITLE
Add Permission To Only Open Panels Through Blocks

### ISSUE THREAD

**Issue by YoshiGalaxy** [rockyhawk64/CommandPanels#200]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Players are able to open panels through the /cpanel command. This allows them to open the gui at anytime, when I'd like it to be restricted to only right clicking assigned blocks. 

### Describe the solution you'd like
Add a permission that specifies whether players can open the panel through the /cpanel command.

### Describe alternatives you've considered
- Setting commandpanel.panel.* to false
- Setting commandpanel.block.add to true

### Additional context
None.

**Comment by jman13378** [comment]
so you can do either
commandpanel.panel.* to false
or
in the panel config do
`panelType:
- nocommand`
> [nocommand This will disable the panel from being used when entering /cp <panel name>.](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#panel-type)
