### ISSUE TITLE
Prefixs

### ISSUE THREAD

**Issue by jman13378** [rockyhawk64/CommandPanels#202]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
No really 
### Describe the solution you'd like
So the paywall messages includes the prefix and what is someone wants to have like [shop] paywall-message
Without changing the global prefix
### Describe alternatives you've considered
Has section with eco command

**Comment by rockyhawk64** [comment]
The prefix is just a default message, a workaround was created from a previous ticket which allowed you to disable the default buy/sell messages and use the `msg=` tag to make a custom message that does not include a default prefix at the front.
