### ISSUE TITLE
[Future]: Open GUI with item frame

### ISSUE THREAD

**Issue by ErythroCraft** [rockyhawk64/CommandPanels#208]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem?
Yes. If a cp is added while looking at an item frame, the block behind the item frame will be activated.

### Solution:
I would like to open cps by clicking on item frames.

Can you give an updated to enable item frames?

Maybe this option already exists and I didn't find it.

**Comment by TheLonelyWolf1** [comment]
For what specific reason do you need the item frame as Panel Opener and why is a block not enough?

**Comment by ErythroCraft** [comment]
Creating shop guis.

Like left or right click on item frames.

![2022-06-16_14 58 03](https://user-images.githubusercontent.com/76217862/174138787-2b5d40ba-8281-47b8-af19-f780a8e9f2f0.png)
![2022-06-16_15 14 46](https://user-images.githubusercontent.com/76217862/174138794-95f305ae-e529-474b-8c6d-f7b9e67155f1.png)
![2022-06-16_15 15 10](https://user-images.githubusercontent.com/76217862/174138795-da1dde6c-bc37-4a47-b8cc-7cc8c1c6b5fc.png)

**Comment by ErythroCraft** [comment]
Thank you very much.

I hope CP it can work for item frames in the future.

**Comment by ErythroCraft** [comment]
@rockyhawk64 
Thank you to give that issue a chance.
Now I going to test the new options.

**Comment by ErythroCraft** [comment]
Can you not set thie to **EntitytargetEvent** ?

Copy paste the target entity data to the file.
" In the game that means looking at entity and than F3+I "

What I mean is ...

1. looking at entity
2. /cpcreate [name]
4. plugins is copying the target entity data
  - [Entity Spigot](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html)
  - [EntityTargetEvent Spigot](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityTargetEvent.html)
[On this part you can copy/paste the entity-ID and all other data the entity has.]
5. creating file

And options to set 
   - isInvisible: true/false
   - isFixed: true/false

I hope you can do this.
