### ISSUE TITLE
A server command to refresh the target player's open panel /cp refresh?

### ISSUE THREAD

**Issue by hypigler** [rockyhawk64/CommandPanels#214]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Its not related to a problem

### Describe the solution you'd like
A command like /cprefresh <player>
In order to refresh the targetted player's open panel (if no panel is open, it does nothing.)

### Describe alternatives you've considered
Uhh no.

**Comment by jman13378** [comment]
I mean /cpr does the same usage

**Comment by kyieran** [comment]
> I mean /cpr does the same usage

but that reloads command panels' configs..? Not refresh the current panel the player has open...

**Comment by Tazler89** [comment]
they can't type a command if they have a panel open...
you can set up refresh intervals and refresh on command

command:
- refresh

**Comment by kyieran** [comment]
This was intended for use with external plugins like denizen.

**Comment by jman13378** [comment]
we dont support denizen so you will have to use /cpr with panels you can use
```yml
commands:
- refresh
```

**Comment by TinyTank800** [comment]
A command for this will be coming probably next update. It is completed and working but the command will be /cpu <Playername> <Position/ALL> which is short for commandpanelsupdate and this will refresh all panels or the panel in that position if the player has a panel open.
