### ISSUE TITLE
Add color support for leather_horse_armor

### ISSUE THREAD

**Issue by RickyLaChow** [rockyhawk64/CommandPanels#216]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Suggestion:
Add the possibility to use leather_horse_armor with  this option leatherarmor: 255,0,255

```
            if (itemSection.contains("leatherarmor")) {
                //if the item is leather armor, change the colour to this
                try {
                    if (s.getType() == Material.LEATHER_BOOTS || s.getType() == Material.LEATHER_LEGGINGS || s.getType() == Material.LEATHER_CHESTPLATE || s.getType() == Material.LEATHER_HELMET) {
                        LeatherArmorMeta leatherMeta = (LeatherArmorMeta) s.getItemMeta();
```

Here there aren't leather_horse_armor, and i can't change the color of leather_horse_armor

**Comment by RickyLaChow** [comment]
This feature has been added in the latest version

**Comment by jman13378** [comment]
Thank you for being patient
