### ISSUE TITLE
disapearing gui

### ISSUE THREAD

**Issue by ViPEk213** [rockyhawk64/CommandPanels#219]
when i create and edit a gui in files folder and reload it gui disapears in my game. its still in folder but when i type /cp (name) its writes that there is no such gui. please help or fix it

**Comment by fireFerry** [comment]
Hello,
This indicates that there is a problem in your panel, probably a yml error. Please send us your panel.
Also, please don't wipe the format next time, it's there for a reason to make us supporting you easier.

**Comment by ViPEk213** [comment]
> 

hello. i didnt change the format its still the yml. 
![image](https://user-images.githubusercontent.com/110340203/182029298-a329c807-d45e-45a6-9897-df4286012f51.png)
![image](https://user-images.githubusercontent.com/110340203/182029312-fc7fcc7e-854d-4e08-a54a-7e578b535a06.png)

**Comment by fireFerry** [comment]
I meant the format on GitHub, which asks you questions. Please send your panel as a file, not as an image.

**Comment by ViPEk213** [comment]
[panel-3.yml.txt](https://github.com/rockyhawk64/CommandPanels/files/9228991/panel-3.yml.txt)

**Comment by ViPEk213** [comment]
[panel-3.yml](https://github.com/rockyhawk64/CommandPanels/files/9229010/panel-3.yml)

**Comment by ViPEk213** [comment]
sorry i closed it as a missclick

**Comment by ViPEk213** [comment]
github dont support fle type .yml

**Comment by ViPEk213** [comment]
[panel-3.txt](https://github.com/rockyhawk64/CommandPanels/files/9229024/panel-3.txt)
i changed file type to txt

**Comment by fireFerry** [comment]
Make sure to use the  `&` character for color codes, and please format your commands/lores as following:
```yml
commands:
- 'command here'
lore:
- 'lore here'
```

**Comment by ViPEk213** [comment]
didnt worked :( 
![image](https://user-images.githubusercontent.com/110340203/182568429-2337ba66-f72b-4f6e-b27a-ba12b1abe217.png)

**Comment by rockyhawk64** [comment]
Use & instead of § and you need to have apostrophes around your lores and commands like this: `"example lore". I have attached your panel with the corrections.
[panel-3.txt](https://github.com/rockyhawk64/CommandPanels/files/9249749/panel-3.txt)
`

**Comment by ViPEk213** [comment]
oh my bad! it worked thank you so much :)
