### ISSUE TITLE
Oraxen Support

### ISSUE THREAD

**Issue by superzyr** [rockyhawk64/CommandPanels#22]
Hi all,

Could we please see in future support added to show customs items from the plugin Oraxen?

Plugin link:
https://www.spigotmc.org/resources/%E2%9C%85-25-%E2%9C%85-oraxen-%E2%98%84%EF%B8%8F-%C2%BB-creativity-extended-%CB%98%E2%96%BE%CB%98-%E2%94%81%E2%98%86%EF%BE%9F-%EF%BD%A5%EF%BD%A1%EF%BE%9F.72448/

Thanks

**Comment by rockyhawk64** [comment]
Will probably not be doing custom item plugins because of the feature Custom Model Data that is already added within CommandPanels.
