### ISSUE TITLE
Custome item in item-paywall=

### ISSUE THREAD

**Issue by KINGGAMER096** [rockyhawk64/CommandPanels#220]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Describe the Issue
A clear and concise description of what the problem is.
I would like to be able to use custome item in item-paywall= e.g  : item-paywall= enchnated cobblestone 1

### Expected behavior
take an enchanted cobblestone then give back 64 cobblestone.

### Versions:
 - Minecraft: [1.16.5]
 - CommandPanels: [3.17.3.1]

**Comment by jman13378** [comment]
please mark no if you haven read the wiki the usage for item-paywall is [here](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/executing-commands/panel-tags#command-tags) 
usage
```
commands:
- item-paywall= [item] [amount]
```
or
```
commands:
- item-paywall= [custom item name]
```

**Comment by KINGGAMER096** [comment]
how do i use the **custome item** ?

**Comment by jman13378** [comment]
[**please refer to the wiki**](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items)

**Comment by KINGGAMER096** [comment]
its giveing me an error can you make an e.g by using item-paywall= [custome item name]

**Comment by jman13378** [comment]
panels:
  eg:
    perm: default
    rows: 3
    title: 'example'
    custom-item:
      idk:
        material: NETHER_STAR
    empty: LIGHT_GRAY_GLASS_PANE
    item:
      '0':
        material: NETHER_STAR
        name: ''
        commands:
        - item-paywall= idk

**Comment by KINGGAMER096** [comment]
oh thank you i didn't know you need to make that thx you should add this in the wiki.

**Comment by jman13378** [comment]
> oh thank you i didn't know you need to make that thx you should add this in the wiki.

its in the wiki
[custom items](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items)

**Comment by KINGGAMER096** [comment]
it don't say where you should add the custome-item cuz i thought you need to use it with the item-paywall=
like, item-paywall= material: 'cobblestone' enchanted: true name: 'cobblestone'  :D lol
