### ISSUE TITLE
Buy and sell commands don't works

### ISSUE THREAD

**Issue by Ggoblink** [rockyhawk64/CommandPanels#221]
Hey i have a problem with buy and sell tags and i don't know how fix that i have vault and an economy plugin so what's wrong ?

**Comment by jman13378** [comment]
Please don't clear the format of the issue
Can you please explain what you mean

**Comment by Ggoblink** [comment]
I was trying to use the buy tag for an panel and the plugin say: an error was found in the configuration commands: buy=

**Comment by jman13378** [comment]
Can tou post your panel file

**Comment by Ggoblink** [comment]
[Bread.txt](https://github.com/rockyhawk64/CommandPanels/files/9234653/Bread.txt)

Its on txt cause github don't support yml

**Comment by jman13378** [comment]
What server software and server version are you running

**Comment by Ggoblink** [comment]
i use Minestrator on 1.18.2

**Comment by Ggoblink** [comment]
I am so sorry that was just vault in the wrong version sorry but i have a question how i put an enchanted item to buy ?

**Comment by jman13378** [comment]
add a [custom item](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items) and use the following
to give that item
```
commands:
- give-item= [itemname]
```
to sell that item
```
commands:
- item-paywall= [itemname]
- commandtorun
```
