### ISSUE TITLE
msg= and /cpc aren't available

### ISSUE THREAD

**Issue by CrazyCloudCraft** [rockyhawk64/CommandPanels#222]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### To Reproduce
1. Go to 'https://www.spigotmc.org/resources/command-panels-custom-guis.67788/download?version=458772'
2. Install that plugin
3. say "/cp" ingame or add a panel with a objekt and a command with
```
commands:
- cpc
- msg= &aHi
```
6. See error

### Expected behavior
That it gives out the message and close the panel like it does before.
/cpc
msg= &aHi

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
![2022-08-02_21 36 31](https://user-images.githubusercontent.com/95505222/182459152-6b81d4ec-7794-4f27-94b8-468757fe4bfe.png)
![2022-08-02_21 37 15](https://user-images.githubusercontent.com/95505222/182459191-0768bc67-fd41-43e9-9d39-898da0b3f55a.png)

### Versions:
 - Minecraft: [1.19.1]
 - CommandPanels: [3.18.1.1]

### Serversoftware:
 - PurPur

### Additional context/Panel files
No further information needed.

**Comment by jman13378** [comment]
can you post your panel file

**Comment by CrazyCloudCraft** [comment]
Yes

**Comment by CrazyCloudCraft** [comment]
[games.zip](https://github.com/rockyhawk64/CommandPanels/files/9245340/games.zip)

**Comment by CrazyCloudCraft** [comment]
It has german language but i think that doesn't matter

**Comment by jman13378** [comment]
can you post the error

**Comment by CrazyCloudCraft** [comment]
Do you mean "Unknown command. Type "/help" for help."

**Comment by CrazyCloudCraft** [comment]
No console errors btw.

**Comment by jman13378** [comment]
this may be a purpur issue because we only test paper and spigot

**Comment by CrazyCloudCraft** [comment]
> this may be a purpur issue because we only test paper and spigot

Yes that's the reason xD

**Comment by CrazyCloudCraft** [comment]
Hello me again, I changed the Software to Paper 
```
This server is running Paper version git-Paper-105 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 4a00cee)
You are running the latest version
Previous version: git-Purpur-1748 (MC: 1.19.1)
```
And i get the same errors. It seems like that this plugin isn't working right on 1.19.1
@jman13378

**Comment by jman13378** [comment]
try using
**commands:
- cpc
- 'msg= &cHey, du kannst dir doch mal ansehen was ich so Programmiere'
- 'msg= &cHier:&9 github.com/CrazyCloudCraft '

**Comment by CrazyCloudCraft** [comment]
ok, but if i start a purpur 1.19.1 server without any modification, the plugin works.

**Comment by CrazyCloudCraft** [comment]
Wow but now i don't know what it could be.

**Comment by CrazyCloudCraft** [comment]
> try using
> 
> ```
> commands:
> - cpc
> - 'msg= &cHey, du kannst dir doch mal ansehen was ich so Programmiere'
> - 'msg= &cHier:&9 github.com/CrazyCloudCraft '
> ```

That dosn't work

**Comment by TinyTank800** [comment]
From you saying that it works on its own. I believe it's another plugin that uses cpc as a command interfering with cp.

**Comment by CrazyCloudCraft** [comment]
some of this plugin is doing this error:
Booster_v6.9.jar
HeadsPluginAPI-3.0.3.jar
TrollingFreedom-2.4.2.jar
LootCrate-0.9.1.jar
unsignedmessages-1.0.0.jar
CommandSuggestion-1.0.0.jar
PerWorldPlugins-1.0.1.3.jar
vanillabosses-2.3.1.jar
EnchantGui-3.7.0.jar
ProtocolLib-586.jar
vilib-1.0.11.jar
QuickShop-5.1.0.9.jar
VotifierPlus-1.0.7.jar
RHSignItem-1.19_R1.jar
VotingPlugin-6.9.3.jar
grimac-2.3.21.jar
smoothtimber-legacy-1.22.1.jar
HeadsInventory-1.11.0.jar
TabList-bukkit-5.6.3.jar

**Comment by CrazyCloudCraft** [comment]
Okey the issues are by the PerWorldPlugins-1.0.1.3.jar

**Comment by CrazyCloudCraft** [comment]
Ahh thanks for all your help @jman13378 and @TinyTank800 
I will close this issue if the dev from PerWorldPlugins reacts to this here

**Comment by CrazyCloudCraft** [comment]
Issue closed. Fixed.
