### ISSUE TITLE
Is it possible to buy 2 commands ?

### ISSUE THREAD

**Issue by Ggoblink** [rockyhawk64/CommandPanels#223]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Describe the Issue
Is it possible to buy 2 command in the same buycommand tag ?

### Expected behavior
i say it

### Screenshots/videos
x

### Versions:
 - Minecraft: [e.g. 1.18.2]
 - CommandPanels: [e.g. 3.18.1.1]

### Additional context/Panel files
x

**Comment by jman13378** [comment]
use this
```
commands:
- paywall= PRICE
- command1
- command2
```

**Comment by Ggoblink** [comment]
thank you verry much :)
