### ISSUE TITLE
Impossible to \ in 1.8

### ISSUE THREAD

**Issue by Kydaix** [rockyhawk64/CommandPanels#224]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
When I use `\` before `"` or `&` in a `msg=`, it does not work! So, the menu is disabled then.

### To Reproduce
1. Use Paper 1.8, Java 17, and CommandPanels 3.18.1.1.
2. Create a simple menu and add an item in it.
3. Add `"msg= &7This is an example: \&7Test!"` in the commands of an item.
4. Reload the plugin.

### Expected behavior
It should returns `This is an example: &7Test!` in the chat.

### Versions:
 - Minecraft: 1.8
 - CommandPanels: 3.18.1.1
 - Java: 17

### Serversoftware:
 - Paperspigot

**Comment by rockyhawk64** [comment]
This is because the YAML regex symbol is \.
`"msg= &7This is an example: \&7Test!"` will not show the \ and the symbol after it will not show.
`"msg= &7This is an example: \\&7Test!"` will show the \ as expected and cancel out the second \.

**Comment by Kydaix** [comment]
However, the first one:
`"msg= &7This is an example: \&7Test!"` does not work! Im' unable to open the menu with.

Then,
`"msg= &7This is an example: \\&7Test!"` shows the `\` but not the `&` that is what I want.
