### ISSUE TITLE
Banner: not accepting placeholders

### ISSUE THREAD

**Issue by Tazler89** [rockyhawk64/CommandPanels#227]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
the banner: function is not using the return values of placeholders.

### To Reproduce
'1':
  material: '%placeholder%' << this works
  banner:
  - '%placeholder%' << don't work
  - '%placeholder%' << don't work

when testing placeholders with papi both return correct text for banner patterns.

### Expected behavior
return placeholder value

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: [1.19,2]
 - CommandPanels: [3.18.1.1]

### Serversoftware:
 - paper
 - waterfall

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by jman13378** [comment]
Try using something like this
```
pre-load-commands:
- set-data= [dataname] %placeholder%
```

**Comment by Tazler89** [comment]
attempted that as well also don't work with cp placeholders

**Comment by jman13378** [comment]
Can you try like refreshing the panel after loading

**Comment by Tazler89** [comment]
done that as well :D i spent 2 hrs trying methods

**Comment by jonjon1322** [comment]
yeah bc `banner:` used to generate the banner and bc cp is parsing the placeholder before loading the placeholder the banner is normal

parsing
```
banner:
- %placeholder%
```
when it should be parsing
```
banner:
- COLOUR,PATTERN
```
This is the only thing i can think of

**Comment by Tazler89** [comment]
Any ideas how to resolve it can it be sorted in plugin to work with placeholders ?

**Comment by jonjon1322** [comment]
i would just use COLOUR,PATTERN

**Comment by Tazler89** [comment]
thats that the placeholders return, just as you have put, i can't pre set them in the .yml as it changes

**Comment by jonjon1322** [comment]
yeah im not sure

**Comment by Tazler89** [comment]
would it be possible to get the dev to look into this :D

**Comment by jonjon1322** [comment]
we will have @rockyhawk64  take a look into this

**Comment by Tazler89** [comment]
@rockyhawk64 Thanks for you hard work and prompt resolution to this, your work is very much appreciated and really helps bring new possibilities to the plugin.

It is working but a small problem, the flag will only work when only the placeholders with data are used.

`material: '%javascript_clanbanner_2%'
        banner:
        - '%javascript_banner_2,0%'
        - '%javascript_banner_2,1%'
        - '%javascript_banner_2,2%'
        - '%javascript_banner_2,3%'
        - '%javascript_banner_2,4%'
        - '%javascript_banner_2,5%'`
![image](https://user-images.githubusercontent.com/51469267/184622292-c6fab6a0-4646-4a65-9ba3-07ab6dece88a.png)

as you know banners can take 6 parts, so when a banner is not using all six the placeholder returns nothing, but it seems when it receives nothing it stops the banner working at all

if i remove the 6th placeholder as shown is not used in the above image, it works fine
![image](https://user-images.githubusercontent.com/51469267/184622638-e17d1d3f-0230-49a4-838d-c18ac62ef62c.png)

**Comment by rockyhawk64** [comment]
Was resolved however ticket not closed until now. Tested in latest build and placeholders are working if using 5 or 6 and all of them will display in a banner.
