### ISSUE TITLE
Cancel block-placement if right clicking the hotbar item while block(s) are in the offhand

### ISSUE THREAD

**Issue by Opalinium** [rockyhawk64/CommandPanels#231]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Some users have found it frustrating when they open their menu via the hotbar item and mistakenly place blocks from their offhand at the same time, due to the event not being cancelled

### Describe the solution you'd like

I would like to request that block-place & interact events be cancelled if fired while the hotbar item is in the mainhand

### Describe alternatives you've considered

As far as I am aware, there would be no solution to this, aside from notifying users to not hold block(s) or item(s) in their offhand while they are navigating the menu via the hotbar item

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/58598304/195509939-0318167e-dfc0-444e-851e-17e76f98a233.mp4

**Comment by jman13378** [comment]
Is this still an occurring issue?

**Comment by TinyTank800** [comment]
Created pull request with fixes to this issue. Hotbar items that are blocks and holding blocks in offhand will no longer place if the held item is a hotbar item.
