### ISSUE TITLE
Do you support mod items with nbt tags? Like Tinkers' Construct mod.

### ISSUE THREAD

**Issue by X-Yunner** [rockyhawk64/CommandPanels#232]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your issue is a duplicate and your problem already has been solved?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### What server version are you running?

1.16

### What CommandPanels version are you using?

3.18.1.2

### What server software are you running?

Mohist

### Describe the Issue

How do I sell items with nbt tags? And when I use the cpg command, I use items with nbt tags to make a menu, and when I reopen the menu, the nbt tags of the items disappear, and they are no longer the items I just placed.

### Expected behavior

I hope to be able to sell items with nbt tags later.

### Additional context/Panel files

   item:
      '30':
        material: TCONSTRUCT_BROAD_AXE_HEAD
        stack: 1
        name: ''
        nbt:
          Material: TCONSTRUCT_TINKERS_BROZNE

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-10-31_00-43-00](https://user-images.githubusercontent.com/56261818/198890567-418a32c9-f751-4d71-bee9-ce7fddb1ee61.png)

**Comment by jman13378** [comment]
Hello! 

Thank you for reaching out but we unfortunately do not support any software other than paper and spigot so you will have to find some other plugin that can do this

Hopefully this has answered your request!

**Comment by rockyhawk64** [comment]
As @jman13378 mentioned, there will be no support for mods, however NBT tags can be added to items, but you will have to determine if it works for your modded items or not https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-settings#item-nbt-data
If you want to sell an item with nbt you will need to make a custom commandpanels item https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items and sell that item with the paywall= and then give-item= command tags.
