### ISSUE TITLE
[Suggestion] Set default way of storing cpanel player heads to the head's value

### ISSUE THREAD

**Issue by Texbio** [rockyhawk64/CommandPanels#235]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

It is a bit annoying having to change each player head manually in the config (using a plugin called HeadsInventory to get the heads ingame to obtain the heads) and would rather this be the default. This would greatly increase productivity when dealing with player heads in guis.

### Describe the solution you'd like

Set default way of storing cpanel player heads to the head value

### Describe alternatives you've considered

I checked the wiki/config and could not find a setting for this. Not sure why its asking for alternatives?

**Comment by jman13378** [comment]
Hello!

Thank you for reaching out but we unfortunately do not support any plugins other than HeadDatabase and the ones on our [dependency page](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/dependencies) so you will have to find some other plugin that can do this

You could use cpdata to save the head value

Hopefully this has answered your request!

**Comment by Texbio** [comment]
Could there be a togglable setting to make the default way of saving heads in guis based on value instead of name?

**Comment by Texbio** [comment]
I did not mean to mark it as complete

**Comment by Texbio** [comment]
Im only using the plugin so I can look up player heads from ingame.

**Comment by jman13378** [comment]
why not use the free HeadDatabase I'm pretty sure it will do what your asking for because it has its own menu

[link](https://www.spigotmc.org/resources/headdb-head-menu-auto-update-free.84967/)

**Comment by TinyTank800** [comment]
I have created a pull request to get an addition added that would make this possibly work. My testing shows it does work but unsure on where it was meant to be placed for it to work properly in production environment.

If you would like to test with it please dm me or open a ticket in the command panels discord. @Texbio
