### ISSUE TITLE
Im trying to do a server selector but i cant seem to get the /server command to work, how do u set that up?

### ISSUE THREAD

**Issue by AwesomeVTO** [rockyhawk64/CommandPanels#24]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes/No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes/No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes/No

### Describe the Issue
A clear and concise description of what the problem is.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: [e.g. 1.16]
 - CommandPanels: [e.g. 3.2.0]

### Additional context/Panel files
Add any other context about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by fireFerry** [comment]
Hello! Please fill in information in the format what it's used for and not type 1 line in the title. you can edit your comment and answer the questions there.

**Comment by rockyhawk64** [comment]
use this as a command:
- server= <server name>

but please remember to fill out the template as it is completely empty
