### ISSUE TITLE
Individual player lore in example_middle_two

### ISSUE THREAD

**Issue by Virologicbody** [rockyhawk64/CommandPanels#240]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Using panel example_middle_two as an example, there is math that is used to determine online players and display them on a certain item on a certain page.

Commands can be attached to those items so when the items are clicked the command successfully runs for that specific online player - I have done this and confirm this is possible and works.

If I try to add a lore for each of these online players, I have been told on Discord to use the 'parseother' placeholder from papi.
%parseother_{username}_{placeholder_without_percent_signs}%

Adding an actual username and a papi placeholder returns the correct placeholder.

When adding '$cp-player-online-%math_1+14*{cp-data-onlinepage}%$' within the papi parseother placeholder as the username, the placeholder fails to display correctly.
I have changed the panels primary and secondary placeholders for both start and end with no successful results.

### Describe the solution you'd like

Be able to set a lore and have it correctly display that lore for that player in that slot without having to specifically specify a username.

e.g. when hovering over an item/player head, be able to display XP level, health etc. correctly for each online player.

### Describe alternatives you've considered

Changing the primary/secondary and start/end placeholders to make sure commandpanels placeholders were started/ended with different characters to papi to stop any 'confusion' within the placeholder.

Opened a ticket in Discord. Ticket-1025

### Screenshots/Videos (you can drag and drop files or paste links)

![Untitled](https://user-images.githubusercontent.com/45987191/208250443-a8e2b629-ba54-47ab-8bc3-0047ee93effc.png)

You can see I have successfully added commands that run for the player using '$cp-player-online-%math_1+14*{cp-data-onlinepage}%$'

**Comment by TinyTank800** [comment]
The issue for these is more how placeholders work. Since the placeholder has so many start stop indicators the parsing of them breaks. I solved this with the newer version of my online panel as I made a custom plugin to handle the placeholder for page and name so its shortened and makes it so you can use other placeholders or commands with it easily. 

Link to download is here: [TinyOnlineV2](https://www.okamisquadron.com/downloads)

**Comment by rockyhawk64** [comment]
Alternative to TinyTank800s solution placeholders can be condensed into data like this:
```YAML
    pre-load-commands:
      - set-data= slot1 $cp-player-online-%math_0:_1+14*{cp-data-onlinepage}%$
    item:
      '2':
        material: STONE
        name: 'Slot 1 of the player viewer'
        lore:
        - '$cp-data-slot1$'
```
