### ISSUE TITLE
tokenpaywall error and success messages

### ISSUE THREAD

**Issue by DoreK333** [rockyhawk64/CommandPanels#241]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [ ] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

3.18.3.0

### What server software are you running?

Purpur

### What happened?

With a successful TokenManager (tokenpaywall) transaction, both transaction success and lack of funds messages are displayed.

### Steps to reproduce the issue

1. Make tokenpaywall function.
2. Have enough TokenManager funds
3. Buy something using function from 1

### Expected behavior

Not displaying insufficient funds message and success message at the same time xD

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/11007700/208320294-f87eb2d4-26e7-41b1-bf43-e75baeb56cdf.png)
(first - insufficient funds, second - success - at the same time)

**Comment by jman13378** [comment]
Can you share your panel file

**Comment by DoreK333** [comment]
```yamlpanels:
  test-token:
    perm: default
    rows: 2
    title: '&lTest menu
    empty: AIR
    emptyID: '0'
    item:
      '0':
        material: ARROW
        stack: 1
        name: '&6Back'
        lore:
        - '&fBack.'
        commands:
        - cpc
        - cp revercoins
      '8':
        material: BARRIER
        stack: 1
        name: '&cClose'
        lore:
        - '&fClose.'
        commands:
        - cpc
      #paywall
      '10':
        material: PHANTOM_SPAWN_EGG
        stack: 1
        name: '&a&lTest paywall'
        lore:
        - '&6• &ftest'
        - '&e1 x &a&lTest&7.'
        - ''
        - '&6• &RC: &e300'
        - ''
        - '&2• &aClick&f'
        commands:
        - tokenpaywall= 300
        - console= broadcast %cp-player-name% test!
        - cpc```

**Comment by jman13378** [comment]
[Within the code](https://github.com/rockyhawk64/CommandPanels/blob/6ed1b170f6f48afde8235f1fb8151fa6996b9a36/src/me/rockyhawk/commandpanels/commandtags/CommandTags.java#L181) we are sending both the failure and success message this should be fixed in the next update
