### ISSUE TITLE
Add the ability to define placeholders on open panel with the API

### ISSUE THREAD

**Issue by Gagafeee** [rockyhawk64/CommandPanels#245]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

From my plugin, I want to open a panel to a player by defining the values of placeholders in the panel

### Describe the solution you'd like

I would like to make : 
`commandPanelApi.getPanel("panel").open(Player, position, data1:4, data2:"aa")`
-> to set the `%data1%` and the `%data2%` to `4` and `aa` in my panel

*I know that syntax is not acceptable in Java, but I don't know exactly how to write it*

### Describe alternatives you've considered

Maybe create a `PanelData` class like
`PanelData pData = new PanelData(String DataName, Object value)`
and insert it like
[...]`.open(Player, position, new PanelData("data1", 4), new PanelData("data2", "aa"))`

**Comment by rockyhawk64** [comment]
You can add a placeholder to a panel using this as an example:
```JAVA
panel.placeholders.addPlaceholder("data1","4");
```
This would make the placeholder %cp-data1% return 4.

**Comment by Gagafeee** [comment]
Oh, ok 😅, thanks I'll add it to my project
