### ISSUE TITLE
Sequences not working within click tags

### ISSUE THREAD

**Issue by RobinRMC** [rockyhawk64/CommandPanels#248]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [ ] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a GitHub issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.18.2

### What Command Panels version are you using?

3.18.6.0

### What server software are you running?

Paper

### What happened?

When you place a sequence tag inside a click tag, Command Panels executes the sequence tag as a command.

### Steps to reproduce the issue

1. Make a command sequence in the panel.
2. Add `left= sequence= ` followed by the sequence name.
3. Observe.

### Expected behavior

The sequence tag gets processed as a tag, instead of a command.

### Error

```shell
None
```

**Comment by jman13378** [comment]
After searching the code, it doesn't seem like this is in the code

**Comment by RobinRMC** [comment]
That means that it was probably overlooked, because `left= msg= ` does work.

**Comment by jman13378** [comment]
`sequence=` is not in our code we know the command takes work but i don't see the sequence tag in our code which means it doesn't exist

**Comment by RobinRMC** [comment]
I'm 100% sure it exists, because the tag works. The thing that doesn't work is when you place a sequence tag inside of a click tag.

I found the code for sequences here: https://github.com/rockyhawk64/CommandPanels/blob/master/src/me/rockyhawk/commandpanels/Utils.java#L136

**Comment by RobinRMC** [comment]
So I should place `left= ` in front of every command in the sequence is what you say?

**Comment by rockyhawk64** [comment]
Yeah if you want all of the commands in the sequence to only execute on left click

**Comment by RobinRMC** [comment]
It works now, thanks. I still think the other way around should also be supported for more customizability.

**Comment by RobinRMC** [comment]
Maybe add the label `enhancement`

**Comment by TinyTank800** [comment]
I believe sequences were phased out in recent updates.

**Comment by rockyhawk64** [comment]
correct sequence= was deprecated as YAML has a built in more advanced method https://github.com/rockyhawk64/CommandPanels/issues/282
