### ISSUE TITLE
feature requests: CP linked to a database

### ISSUE THREAD

**Issue by Lucifer187** [rockyhawk64/CommandPanels#25]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes,this is only local

### Is your feature request related to a problem? Please describe.
no, a wish

### Describe the solution you'd like
I am trying to run a bungeecord server and would like to include some functions in CP

### Describe alternatives you've considered
I haven't thought much about that yet

### Additional context
-

**Comment by rockyhawk64** [comment]
There is a plugin called Auto-Sync and while I have not downloaded it for myself I am looking into that as a possible hook for syncing panels throughout servers.
https://www.spigotmc.org/resources/auto-sync-synchronize-server-files.73893/
