### ISSUE TITLE
Output Value seems to be ignored

### ISSUE THREAD

**Issue by RobinRMC** [rockyhawk64/CommandPanels#252]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [ ] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a GitHub issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### Server version

1.18.2

### Command Panels version

3.18.6.1

### Server software

Paper

### What happened

`output: false` inside a has section seems to be getting ignored / not processed.

### Steps to reproduce the issue

1. Check for a permission using a has section.
2. Add a new line containing `output: false` inside the has section.
3. Save the file.
4. Run `/cpr` in the server.
5. Test the permission.
6. Observe.

### Expected behavior

The expected behavior would be that `output: false` reverses the conditions so that it executes when the player does **not** have the specified permission.

**Comment by TinyTank800** [comment]
Output is no longer used. You use NOT before whatever the check is example NOT %cp-player-name% HASPERM

**Comment by RobinRMC** [comment]
Oh, okay. Thanks, I'll try that.

Maybe update the wiki. 😋
https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-sections#output-value

**Comment by RobinRMC** [comment]
Using `NOT` in front of the condition works. Thanks!
