### ISSUE TITLE
rightshift and leftshift not working with middle or bottom panels

### ISSUE THREAD

**Issue by roracle** [rockyhawk64/CommandPanels#259]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

3.18.3.0

### What server software are you running?

PaperMC

### What happened?

The leftshift and rightshift seems to not work at all in a `has` section. I've tested this in every panel (top, middle, bottom)
I thought at first it was an issue with the bottom panel, but then it didn't work in the middle panel.

In addition, leftshift and rightshift do not appear to work **_at all_** if they are in {Bottom} or {Middle} position, `has` or no `has`. I will experiment with this more, but that appears to be the case thus far.

### Steps to reproduce the issue

Have three menus, top middle and bottom, give them leftshift or rightshift executions, along with others in `has` sections and watch them not work except the one without `has` in the top position.

### Expected behavior

leftshift and rightshift should work regardless of being in a `has` section and regardless of their panel location.

### Error (optional)

```shell
There are no errors, it simply does not work.
```

**Comment by roracle** [comment]
Edit: This version is 3.19.0.3
Paper build 45 for 1.20.1

**Comment by TinyTank800** [comment]
Could you also send the panel file you are using so we can test using that exact file?

**Comment by TinyTank800** [comment]
This seems to be an issue with newer mc versions and changes to client vs server accessable information.

**Comment by rockyhawk64** [comment]
middle and bottom sections are part of the inventory and not the top GUI area which has different abilities so this is not possible.
