### ISSUE TITLE
Dupe 1.8.8

### ISSUE THREAD

**Issue by Antoniova1** [rockyhawk64/CommandPanels#261]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.8

### What CommandPanels version are you using?

3.18.3.0

### What server software are you running?

PaperMC

### What happened?

there is a type of duplication in version 1.8.8, I have a panel where to buy an item with item-paywall= IRON_INGOT 4, if I have exactly 4 iron ingots I can infinitely buy that item and it will never remove those four items, but if I have more than 4 iron ingots in my inventory if I remove it correctly until I reach 4 and it becomes infinite again, I was using a paper fork but I changed to the original and the exact same thing happened, I changed to the spigot version normal and the same thing happens, I'm using the latest version of command panels

### Steps to reproduce the issue

happens with any item either with the name or with the ID

### Expected behavior

I hope that the items can be removed from the inventory, and that this eternal duplication does not happen

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-05-02_23 35 46](https://github.com/rockyhawk64/CommandPanels/assets/108409110/9a67004c-6fd9-4af2-a565-b59b8105f625)
![2023-05-02_23 36 00](https://github.com/rockyhawk64/CommandPanels/assets/108409110/064a011e-3f72-4b01-97ba-f2b334ec9c19)

**Comment by TinyTank800** [comment]
Related to other issue
https://github.com/rockyhawk64/CommandPanels/issues/203

**Comment by TinyTank800** [comment]
Should be fixed in next pull release from me.

**Comment by Antoniova1** [comment]
> Should be fixed in next pull release from me.

Thank you very much
