### ISSUE TITLE
Make new Wiki more readable

### ISSUE THREAD

**Issue by MadPanCake** [rockyhawk64/CommandPanels#264]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Hi!

The wiki page is kinda difficult to read, due to being stretched through entirety of the screen width, which makes it difficult to read, exhausting and overwhelming.
Compare it with the old wiki and you see just how much more relaxed you are reading it, compared to the new layout.

Another thing is the fact that the new wiki is lacking some (important) content from the old wiki.

### Describe the solution you'd like

Make the layout more in-line with other websites, without overwhelming entire screen with huge font size and occupying literally all of the possible space.

### Describe alternatives you've considered

Using the previous Wiki. I actually always use the old wiki. I don't like the new one, it's difficult to find information.

**Comment by TinyTank800** [comment]
Which information is missing in the new wiki?
