### ISSUE TITLE
Opening Panels via API triggers PanelClosedEvent directly

### ISSUE THREAD

**Issue by xMrAfonso** [rockyhawk64/CommandPanels#265]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

IMPORTANT: The version is actually 1.20.1 but couldn't select it.

When opening a (multi) panel via the API, it seems to trigger the PanelClosedEvent twice and the whole GUI stops working, I am able to remove items from it, clicking on items doesn't work. Once I click on a panel that is on the player's inventory, it automatically vanishes.

### Steps to reproduce the issue

1. Create a command for example, that opens a specified (multi) panel.
2. Listen to the PanelClosedEvent, print/broadcast a message
3. You will see that when opening a panel, it triggers the PanelClosedEvent and everything stops working. 

### Expected behavior

It was expected to open the specified (multi) panel to the player without any issues.

**Comment by jman13378** [comment]
can you post your jar file or java classes

**Comment by xMrAfonso** [comment]
Hi there, so I tested it a bit, and it does seem that I explained the issue completely wrong, I am sorry.

For context, this does NOT happen when executing it via commands, etc. specifically.
I am trying to override a menu from another plugin, and to do that, I used the following:
https://paste.helpch.at/nicarohoci.java

And here is a gif of what exactly happens: https://i.imgur.com/7ZfUD2V.gif

**Comment by xMrAfonso** [comment]
After some more testing, delaying the panel open by 1 tick seems like it fixed the issue with the panel not working, although PanelClosedEvent is still being called once.
