### ISSUE TITLE
conviert bossshoppro to commandpanels

### ISSUE THREAD

**Issue by dinobossytnew** [rockyhawk64/CommandPanels#266]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Is it possible to import or convert menus created in BossShopPro to CommandPanels? If so, it would be perfect, don't you think? Since BossShopPro is a very old plugin without any support anymore, it would be fantastic if they could add an easy-to-use converter that might not be perfect, but could migrate as much as possible.

### Describe the solution you'd like

The thing is, I have 49 menus created in BossShopPro and I wanted to migrate or import them.

### Describe alternatives you've considered

chatgpt using plugin version the 2021 :( verry low version and not perfect ;(

**Comment by rockyhawk64** [comment]
Thanks for the suggestion about importing BossShopPro menus into CommandPanels. While it sounds like a cool idea and would save time, it will take time and effort to develop as it converts the data structures and is too niche to officially add.
