### ISSUE TITLE
Items are being removed from panel in online editor

### ISSUE THREAD

**Issue by yogg-soggot** [rockyhawk64/CommandPanels#267]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [x] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

When editing panel online if you enter commands on open all of the items in panel disappear.
Same happens when you edit commands to open and commands on close.

### Steps to reproduce the issue

1. Go to https://commandpanels.net/editor
2. Add items to the panel
3. Edit Commands To Open, Commands On Open, or Commands On Close
4. All items are removed from the panel

### Expected behavior

1. Go to https://commandpanels.net/editor
2. Add items to the panel
3. Edit Commands To Open, Commands On Open, or Commands On Close
4. All items stay in place

**Comment by rockyhawk64** [comment]
I was able to reproduce the issue in the production environment, but not in the development environment. It seems that the code updates for the Panel Settings window were not reflected in production, even though the Item Settings window was updated successfully in a previous deployment.
However, I can confirm that the issue has been resolved following the latest deployment.
