### ISSUE TITLE
Placeholder API exceptions

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#27]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
No

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug

New placeholder API versions no longer accepting null 

### To Reproduce
1. Use placeholder API 2.10.7 or higher

### Expected behavior

Plugin goes RIP

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: ALL
 - CommandPanels: ALL including classic

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by fireFerry** [comment]
1ea62d8

**Comment by rockyhawk64** [comment]
Command Panels Classic v2.11.0 has the fix for that version.

**Comment by rockyhawk64** [comment]
Done
