### ISSUE TITLE
Implement refresh interval for gui title

### ISSUE THREAD

**Issue by kokqi** [rockyhawk64/CommandPanels#270]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [x] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Oh ok

### Describe the solution you'd like

Like that

### Describe alternatives you've considered

As described

**Comment by TinyTank800** [comment]
Added for 1.20+ [https://github.com/rockyhawk64/CommandPanels/issues/308](url)
