### ISSUE TITLE
Maybe some geyser support?

### ISSUE THREAD

**Issue by MeowkaTheCat** [rockyhawk64/CommandPanels#272]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

I suggest the plugin to make gui in bedrock geyser clients to look the same as java. I have a minecraft server with commandpanels and geyser installed. Everything is fine but the gui in bedrock looks ugly

### Describe the solution you'd like

New resource pack or feature in the plugin

### Describe alternatives you've considered

A resource pack would change the look of gui in bedrock, or it would be rIght in the plugin

**Comment by TinyTank800** [comment]
The conversion of items from Java to bedrock is handled by guyser, so we don't really have control over how it looks between the 2. Unsure if there are resource pack plugins that support guyser, but if so, you may be able to do what you suggested and make a parity pack to get them to look similar to the Java edition.
