### ISSUE TITLE
Change NBT check path to vanilla NBT

### ISSUE THREAD

**Issue by H1sho** [rockyhawk64/CommandPanels#276]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

If you add nbt data to item or you want to check it with placeholders provided by plugin it refers to nbt data with non vanilla pathway - instead of path to <Item>..tag you get:  <Item>.tag.{PublicBukkitValues: {"commandpanels:<your_nbt>":"<value>"}} which is quite uncomfortable to use in vanilla like projects.

### Steps to reproduce the issue

Use /data command on item and you see the problem in pathway

### Expected behavior

Default pathway instead of modified one because it's quite useless in current form

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/rockyhawk64/CommandPanels/assets/121500372/97ee4240-6847-4be4-a06c-bb8d2daa31a1)

**Comment by TinyTank800** [comment]
So i have created a dev build with these changes applied. After testing it seems to add the nbt correctly using vanilla paths. Im going to attach the file and you may test around with it. PLEASE ONLY USE THIS BUILD IN TEST SERVERS AS CHANGES ARE NOT FINAL AND MAY CONTAIN BUGS.
[CommandPanels-DEV.zip](https://github.com/rockyhawk64/CommandPanels/files/14152599/CommandPanels-DEV.zip)

**Comment by TinyTank800** [comment]
```YAML
      example1:
        material: STONE
        name: '&6Test'
        stack: 5
        nbt:
          ndex:
            type: short
            data: '%cp-player-name%'
            sub-data: {}
          palette:
            type: string
            data: none
            sub-data: {}
            ``` Heres an example of how to setup nbt now
