### ISSUE TITLE
itemType: - removeItem not working

### ISSUE THREAD

**Issue by MathiewMay** [rockyhawk64/CommandPanels#277]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.20

### What CommandPanels version are you using?

3.19.1.7

### What server software are you running?

PaperMC

### What happened?

The itemType: - removeItem does not work.

While the dropItem itemType works the removeItem itemType does not work as stated in the [wiki](https://commandpanels.net/wiki?groupIndex=3&index=0).

### Steps to reproduce the issue

1. Make a new panel
2. Give a slot the itemType: - placebale and - removeItem
3. Open the panel
4. Place an item in the specific slot
5. Close the planel
6. Notice that the item has not been placed in the players inventory as stated on the [wiki](https://commandpanels.net/wiki?groupIndex=3&index=0).

### Expected behavior

1. Make a new panel
2. Give a slot the itemType: - placeable and - removeItem
3. Open the panel
4. Place an item in the specific slot
5. Close the panel
6. The item in the specifc slot should be placed in the players inventory the same way the [wiki](https://commandpanels.net/wiki?groupIndex=3&index=0) states and the same way a crafting table places items that are still in the GUI screen back into the players inventory.

**Comment by rockyhawk64** [comment]
Can you try it again but also include the itemType:
`noNBT #this will remove the NBT from items in panels, so they will not be removed if taken out of the GUI`

**Comment by JuanCalle1606** [comment]
This won't be fixed?

**Comment by TinyTank800** [comment]
The website needs updated. The tag is actually returnItem now.
