### ISSUE TITLE
HeadsDatabase heads not working anymore!

### ISSUE THREAD

**Issue by Strahilchu** [rockyhawk64/CommandPanels#279]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur

### What happened?

Custom heads from /hdb used to work in menus but now they do not!

### Steps to reproduce the issue

Place any custom head into a chest.
Run /CPG and click chest to turn it into a menu.
Open the menu, heads will not show and in the config it will only show cps= HeadsDatabase

### Expected behavior

For heads to appear as before

Not sure if relevant but I am running the server on Java version: 21.0.1+12-LTS

**Comment by TinyTank800** [comment]
You will need to manually set them as of right now but i have created a pull request which should auto set values for player heads using /cpg but unsure when the update will come out.

If you would like to test with these changes please dm me or open a ticket inside the command panels discord and i can send the jar I used with the changes. @Strahilchu
