### ISSUE TITLE
Request add damaged items

### ISSUE THREAD

**Issue by TravisC671** [rockyhawk64/CommandPanels#28]
Have you checked the wiki page to see if your suggestion is already added?
yes

Have you checked the issue tracker to see if your suggestion was already submitted and denied?
yes

Have you asked if the feature already exists in the Discord Server? (Or got redirected to a Github issue here)
no

Is your feature request related to a problem? Please describe.
yes, when we put in items that had been damaged, the damage was not saved

Describe the solution you'd like
you cant save panels with damage, and it would be fixed the same way the enchantment 

Describe alternatives you've considered
N/A

Additional context
N/A

Edited By Moderator: There are premade templates premade to help staff not need to ask excessive follow up questions about issues and suggestions.
yeah sorry :)

**Comment by rockyhawk64** [comment]
Do you mean damaged items?

**Comment by TravisC671** [comment]
Yes, I looked on the wiki but I couldn’t see anything about it

**Comment by fireFerry** [comment]
That wasn't the only question. Please edit your first comment and answer all questions.

**Comment by TravisC671** [comment]
Ok

**Comment by TravisC671** [comment]
i edited it

**Comment by fireFerry** [comment]
It's not currently possible to have items with damage in panels.

**Comment by TravisC671** [comment]
so will it be added soon, or probably not.

**Comment by fireFerry** [comment]
I turned the issue into a feature request now, and assigned the developer to look at it. I don't know if it would take priority because it isn't a much wanted feature and I personally don't see a purpose for it.

**Comment by TravisC671** [comment]
hey thank you so much! we use the damage on items for our texturepacks!

**Comment by fireFerry** [comment]
You should switch to using custom model data. That is supported by cp and is a better way then using durability

**Comment by fireFerry** [comment]
I think item durability will not be added because cp already has the ability to use custom model data for items.

**Comment by rockyhawk64** [comment]
I will be adding this. Custom Model Data is not worth just adding damage to items.

**Comment by TravisC671** [comment]
Thank You! our texture pack is huge and it would be a massive project to convert them all. this is a huge help thank you!

**Comment by rockyhawk64** [comment]
This has now been added in v3.7.0
here is an example:
```YAML
      '9':
        material: LEATHER_CHESTPLATE
        name: '&9&lBLUE'
        leatherarmor: BLUE
        damage: 20
```
