### ISSUE TITLE
Hotbar Items, custom items

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#29]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Allow for more customization when using open-with-item.
Create a new Void that contains ItemStack creation, link it with items in the GUI so that there is no duplicate code and it is standardized.
EG:
- Custom Heads
- Custom Maps
(maps folder with custom images 128x128 size for the maps)
- Custom Model Data
- Coloured Leather Armor
- Potion Types
- Enchantments
- Etc...

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by rockyhawk64** [comment]
Added.

**Comment by AXL00** [comment]
Hi, I didn't know where to ask for help. When using a custom head with cps= <value> in an open with item, when using the command panel, the item panel does not work, in fact, it can move through the inventory as a normal item.

**Comment by AXL00** [comment]
please help

**Comment by TinyTank800** [comment]
Do you have stationary: Inside it?

**Comment by TinyTank800** [comment]
Also you can watch my tutorial on it for help. https://youtu.be/dcA2FCR6ABM
