### ISSUE TITLE
Custom inventory interaction to opens GUI

### ISSUE THREAD

**Issue by SterlStoc** [rockyhawk64/CommandPanels#292]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

new players in my server sometimes don't know what commands available to open any custom GUI in game and needs to either ask experience players / open provided commands list on wiki which by them is not user friendly. Especially when encountering newbie Minecraft players.

Thus, they suggest to me if I could make the a functionality that can open GUI without typing commands, Can be open anywhere, anytime, and without interrupting player's vanilla inventory slot/texture.

### Describe the solution you'd like

my suggestion is to make players click anywhere outside of the inventory GUI to open a custom GUI.
This can be achieve in clickInventoryEvent = null to trigger a GUI to open, said by another developer who made the functionality 
![image_2024-02-02_115030347](https://github.com/rockyhawk64/CommandPanels/assets/158534879/acd20447-1c55-48ef-af35-5fd25e89823b)

### Describe alternatives you've considered

another way is to maybe make the click slot < 0 to opens a GUI

### Screenshots/Videos (you can drag and drop files or paste links)

this clip is the example on how it works in-game
https://youtu.be/gJZlxQilUYs?start=314&end=322

**Comment by TinyTank800** [comment]
My bad. We actually have this feature.
![image](https://github.com/rockyhawk64/CommandPanels/assets/22015094/5e39c3bb-9299-42af-bd68-4621bcca3225)

**Comment by SterlStoc** [comment]
ahh awesome! thank you!

**Comment by SterlStoc** [comment]
will try it out soon!

**Comment by SterlStoc** [comment]
Hi! sorry for re-opening the suggestion
I want to know, since "Panel Outside Commands" only works on custom panel and not in player inventory itself.
Is there a way to execute that feature in just player's inventory?
if no, I would like to suggest a config settings for it. 

Since this can only works by opening 1 panel only
I would like to suggest adding this feature in `config.yml` with this settings

`open-on-outside-inventory: panelName`
_#this will open the 'panelName' when a player clicking outside of their inventory_

just like this clip shown before
https://youtu.be/gJZlxQilUYs?start=314&end=322

it works the same as `outside-commands`
but, instead of per custom panel, it only works on player's inventory 

hope this won't be a hassle, thank you

**Comment by TinyTank800** [comment]
So like all the time even without panels open if they click it goes to that panel?

**Comment by SterlStoc** [comment]
my bad, maybe not all the time exactly
how about 

```
open-on-outside-inventory: true/false
- panel: panelName
```

**Comment by SterlStoc** [comment]
hello! my apologise for like begging at this point, but is there anything I could help to add this feature to be considered?
thank you

**Comment by TinyTank800** [comment]
I will look into implementing some form of this right now.

**Comment by SterlStoc** [comment]
appreciates it!
I shall support aswell even via patreon since I have been actively using this plugin for my server for like 2 years now ^^

**Comment by SterlStoc** [comment]
I've looked into the code from the clip on the post above, I believe this is how they do it?
https://github.com/Athlaeos/ValhallaTrinkets/blob/master/src/main/java/me/athlaeos/valhallatrinkets/menus/TrinketMenu.java

```
    public void handleMenu(InventoryClickEvent e) {
        e.setCancelled(true);
        Inventory clickedInventory = e.getClickedInventory();
        if (clickedInventory != null){
            if (clickedInventory instanceof PlayerInventory && (e.getClick() == ClickType.LEFT || e.getClick() == ClickType.RIGHT)) {
                e.setCancelled(false);
```

**Comment by TinyTank800** [comment]
I believe rocky got the feature close to done and will be released probably in next update.

**Comment by SterlStoc** [comment]
oh okay, my apologise for bothering ^^"
thank you so much for the work!

**Comment by TinyTank800** [comment]
This was added in the latest release of commandpanels. Outside commands now can be executed without a panel open.
