### ISSUE TITLE
NBT Enhancements

### ISSUE THREAD

**Issue by TinyTank800** [rockyhawk64/CommandPanels#294]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

NBT auto generation is working now and seems to be causing errors with minecraft clients. See linked message

### Steps to reproduce the issue

/cpg with any item

### Expected behavior

Should save only CUSTOM nbt not names material or the such

### Error (optional)

```shell
https://discord.com/channels/602338405883314206/749407995036696656/1204211095514906654
```

### Other files, you can drag and drop them here to upload. (optional)

https://discord.com/channels/602338405883314206/749407995036696656/1204211095514906654

### Screenshots/Videos (you can drag and drop files or paste links)

https://discord.com/channels/602338405883314206/749407995036696656/1204211095514906654

**Comment by TinyTank800** [comment]
Changing this to enchancement as it will be a rework of the new system now.
Idea:
make it so it checks what data is inside the nbt and clear anything from the list thats default to commandpanels types like material: stack: and such.
Another addition for this enchancement is nbt values should be checked as what type they are and saved as that type are right now ALL nbt is being saved as string.

**Comment by rockyhawk64** [comment]
https://www.spigotmc.org/resources/commandpanels.67788/update?update=548629
Think was all covered here in this recent update.
