### ISSUE TITLE
Error Items dont drop when player dies

### ISSUE THREAD

**Issue by Mdsh9** [rockyhawk64/CommandPanels#296]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur 1.19.4

### What happened?

When a panel have a item for open it in the hotbar, the player can't drop anything when he dies.
But when the player don't have the item for open the panel, the items drop normally

### Steps to reproduce the issue

1. Create a panel with "open-with-item", the item needs to open the panel
2. Now die with items in your inventory.
3. Lose all the items.

### Expected behavior

1. Create a panel with "open-with-item", the item needs to open the panel
2. Now die with items in your inventory.
3. Lose all the items.

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/9YTpIqaLJS4

**Comment by Mdsh9** [comment]
I try it in Paper 1.19.4 and it happens to.

**Comment by TinyTank800** [comment]
This is a bug and probably has to do with our new nbt change. I will look into this when I have time.

**Comment by Mdsh9** [comment]
Thank you, great plugin for being free, awesome job!

**Comment by TinyTank800** [comment]
Created a pull for this fix. Rocky will update when he has time.
