### ISSUE TITLE
CommandPannels causing a lot of lag in my server (1.15.2)

### ISSUE THREAD

**Issue by austv** [rockyhawk64/CommandPanels#30]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
The plugin seems to be consuming a lot of the server's tick, as shown below.

### Expected behavior
I expected it to consume less of the TPS of my server.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: [e.g. 1.15.2]
 - CommandPanels: [e.g. 3.5.0]

### Additional context/Panel files
https://pastebin.com/c0tkCgiz    -    Here's a timings report showing what specifically is causing the lag

**Comment by fireFerry** [comment]
Can you send us your config file please?

**Comment by austv** [comment]
Sure, here it is:
config:
  version: '3.0'
  refresh-panels: 'true'
  panel-blocks: 'true'
  refresh-delay: '4'
  stop-sound: 'true'
  disabled-world-message: 'true'
  update-notifications: 'true'
  panel-snooper: 'false'
  ingame-editor: 'true'
  input-cancel: cancel
  input-cancelled: '&cCancelled!'
  input-message:
  - '%cp-tag%&aEnter Input for Command'
  - '&cType &4%cp-args% &cto Cancel the command'
  format:
    perms: '&cNo permission.'
    reload: '&aReloaded.'
    nopanel: '&cPanel not found.'
    noitem: '&cPanel doesn''t have clickable item.'
    notitem: '&cPlayer not found.'
    error: '&cError found in config at'
    needmoney: '&cInsufficient Funds!'
    needitems: '&cInsufficient Items!'
    bought: '&aSuccessfully Bought For $%cp-args%'
    sold: '&aSuccessfully Sold For $%cp-args%'
    tag: '&6[&bCommandPanels&6]'
    offline: Offline

**Comment by fireFerry** [comment]
try putting refresh-panel delay higher or disable refresh-panels

**Comment by rockyhawk64** [comment]
And also disabling panel-blocks

**Comment by FlirtyMomma** [comment]
Love that I found this. I'm having the exact same issue.


https://timings.aikar.co/?id=976381eb9ea44fd4813d26566f06202b#plugins

**Comment by fireFerry** [comment]
@FlirtyMomma You are not using the right java flags for your server. Fix that first: https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by FlirtyMomma** [comment]
I know this too. I am also, talking to my host about changing that.

**Comment by FlirtyMomma** [comment]
I know this too. I am also, talking to my host about changing that.

**Comment by fireFerry** [comment]
and most lag is when the player opens a menu, not all the time

**Comment by fireFerry** [comment]
Ticket will be closed due to issue being fixed.
