### ISSUE TITLE
ItemPaywall does not require full amount

### ISSUE THREAD

**Issue by Endershadow21** [rockyhawk64/CommandPanels#302]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

I have an item paywall for a GUI on my server. The paywall requires 20 items to execute a command in the GUI. However, the player is able to execute the command with only 50%-100% of the items in their inventory. So the player can use 10 items to execute the command. If the player has 30 items in their inventory, they can execute the command twice even though the paywall requires 40 total items. The .yml used in example is submitted here as .txt file.

### Steps to reproduce the issue

Use itempaywall on a command in a panel and set the requirement.
Try executing the command with only 50% of the requirement.

### Expected behavior

The itempaywall will allow you to execute the command with any amount of items between 50% and 100% of the itempaywall requirement. This has been tested using MMOItems custom items.

### Other files, you can drag and drop them here to upload. (optional)

[windbuy.txt](https://github.com/rockyhawk64/CommandPanels/files/14813971/windbuy.txt)

### Screenshots/Videos (you can drag and drop files or paste links)

<img width="253" alt="image" src="https://github.com/rockyhawk64/CommandPanels/assets/165534398/f82389b8-0a4a-46bb-abab-389cca235722">
<img width="257" alt="image" src="https://github.com/rockyhawk64/CommandPanels/assets/165534398/5009388b-cf23-4f3d-bbab-1bd6f23c17c1">
<img width="291" alt="image" src="https://github.com/rockyhawk64/CommandPanels/assets/165534398/e3bb523c-31ee-4baa-bd48-84ad6f18c969">
<img width="398" alt="image" src="https://github.com/rockyhawk64/CommandPanels/assets/165534398/c736a33a-96af-4bd1-84d9-d1dd74d00318">

**Comment by TinyTank800** [comment]
Seems to only be an issue relating to mmo= items being used.

**Comment by TinyTank800** [comment]
Can you test using this dev build? I think i found the issue and have made a fix for it but i cant test it with mmo items.

**DO NOT USE IN PRODUCTION/LIVE USE!**
[CommandPanels-DEV.zip](https://github.com/rockyhawk64/CommandPanels/files/14894332/CommandPanels-DEV.zip)

**Comment by Endershadow21** [comment]
Yes, we will test it and I'll get back to you later today if I can. Thank
you!

Endershadow21
