### ISSUE TITLE
change gui title 1.20+

### ISSUE THREAD

**Issue by killertuling** [rockyhawk64/CommandPanels#308]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

In version 1.20,paper has added a new method InventoryView#setTitle.  I think it is already possible to change the gui title,but i'm not sure for it,  I want  use it to make some gui background animation effects

### Describe the solution you'd like

new tag for change GUI's Title、Refresh Title when gui's title has placeholder

### Describe alternatives you've considered

nothing

### Screenshots/Videos (you can drag and drop files or paste links)

https://jd.papermc.io/paper/1.20/org/bukkit/inventory/InventoryView.html#setTitle(java.lang.String)

**Comment by TinyTank800** [comment]
I have managed to get this working with animate values and has sections updating as well as placeholders will also update.

I will also be looking into adding a panel-title= command tag.
![Recording 2024-05-04 at 11 42 02](https://github.com/rockyhawk64/CommandPanels/assets/22015094/c4ce75eb-0b0b-44e4-826b-fb354094f48c)
