### ISSUE TITLE
Nbt placeholder returning empty for anything but string values.

### ISSUE THREAD

**Issue by TinyTank800** [rockyhawk64/CommandPanels#310]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

When using nbt placeholder it returns empty for anything but string values.

### Steps to reproduce the issue

Use nbt placeholder

### Expected behavior

Return value in whichever representor it needs.

probably need to check for every type and break when found.

**Comment by rockyhawk64** [comment]
In version 3.21.3.0 now supporting string, integer, double, float, long, short, boolean, byte.
