### ISSUE TITLE
Bedrock different material

### ISSUE THREAD

**Issue by Artriix** [rockyhawk64/CommandPanels#311]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Yes, limitations frpm bedrock.

### Describe the solution you'd like

I would like to suggest that you can make an item different for a bedrock player to solve the problem of them not being able to see custom heads.

### Describe alternatives you've considered

For example:
  material: cps = asasjdasod9jasod (For java)
  bedrock-material: compass

**Comment by rockyhawk64** [comment]
Currently there are no plans for any bedrock support through Geyser outside using Floodgate Forms, as traditional GUIs used in java are not ideal in Bedrock.
There is info on the CommandPanels wiki here https://commandpanels.net/wiki?groupIndex=6&index=0&version=1.13+-+1.20
![form](https://i.imgur.com/3rj2OQ2.png)

**Comment by Artriix** [comment]
@rockyhawk64 Is there the possibility of showing different panels for bedrock or java and it is not possible to show a different material???
