### ISSUE TITLE
ChangeFormas....

### ISSUE THREAD

**Issue by dinobossytnew** [rockyhawk64/CommandPanels#318]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

Old and new panels.

### Describe the solution you'd like

They would stop changing the damn format of the panels every 10 updates if the competition added a converter and people switched because their plugin doesn't compete, doesn't generate competition, instead of improving their plugin, they screw over those who use it and their own community bunch of idiots. I say this more as criticism than as a suggestion: stop modifying or changing spaces in these panels because seriously it's very annoying, even the YouTuber Ajneb97 mentions it and it's clear there's a very big problem when they change the panel configuration format every 10 updates, a breakdown that you have to contact support via Discord to fix sometimes... it's a headache and I think we're at a standstill where either CommandPanels dies or its community disappears. Why? Because they keep modifying the panel file so you have a panel from 10 old versions, update it, and the panel dies, 20 errors pop up, there's no solution other than going back to read the wiki, seriously it's stressful and I think you're also realizing it, now with the release of ZMenus do you think if you don't add something that shows you won't modify the panel configurations people will leave? Honestly, they add animations and I'm out, I'll delete CommandPanels and switch to ZMenus. I'm saying this as something that the developers should have realized, losing the community isn't profitable, your solution to avoid migrations is effective... to the point that no plugin can convert to ZMenus or DeluxeMenus their panels, but it's so effective that sometimes it screws over their own. Best regards.

### Describe alternatives you've considered

Stop changing formats unnecessarily is the change, literally speaking. It's not about adding something; it's about playing with spaces every 10 updates.

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=spxnyY7lY0Q  Wake up and stop changing formats, seriously, leave them or more people will disappear than just me... who are already switching to ZMenus and looking into better things than what I'm looking into, like animations.

old https://www.youtube.com/watch?v=RT92gDl7IyU

**Comment by TheLonelyWolf1** [comment]
Can you elaborate on what bothers you exactly in the recent changes of Command Panels?

**Comment by TinyTank800** [comment]
I would like to point out that we do not run or make commandpanels to be profitable. We simply make the plugin to be useful for server developers and improve the plugin based on usage issues and user input. The only major changes I can think of were has sections, which was quite a while ago. Other changes that come up may be formatting for reworked features. With these changes, we make a major release and explain what changed in each update. We always recommend that you test panels when a major update is done on your servers. If you have any suggestions for how we can fix or improve the formatting, please explain them clearly as this issue reads more as a rant than a suggestion. I understand that frustration can arise from major changes if they break some panels, but we don't force people to update and always suggest testing panels before doing the major jumps.

If you need any help fixing or updating some formats, please join the discord and create a ticket. We will help as much as we can to make it as painless as possible to fix these issues.

**Comment by dinobossytnew** [comment]
> Me gustaría señalar que no ejecutamos ni fabricamos paneles de comando para que sean rentables. Simplemente hacemos que el complemento sea útil para los desarrolladores de servidores y lo mejoramos en función de los problemas de uso y las aportaciones del usuario. Los únicos cambios importantes que se me ocurren fueron las secciones, lo cual ocurrió hace bastante tiempo. Otros cambios que surjan pueden ser el formato de las funciones reelaboradas. Con estos cambios, hacemos un lanzamiento importante y explicamos qué cambió en cada actualización. Siempre recomendamos que pruebe los paneles cuando se realice una actualización importante en sus servidores. Si tiene alguna sugerencia sobre cómo podemos corregir o mejorar el formato, explíquela claramente, ya que este problema parece más una perorata que una sugerencia. Entiendo que puede surgir frustración por cambios importantes si rompen algunos paneles, pero no obligamos a las personas a actualizar y siempre sugerimos probar los paneles antes de realizar los saltos importantes.
> 
> Si necesita ayuda para arreglar o actualizar algunos formatos, únase a Discord y cree un ticket. Ayudaremos todo lo que podamos para que solucionar estos problemas sea lo más sencillo posible.

Hello, we, the server configurators, do not develop or do little and sometimes little programming, as most upload things to Spigot premium and free. This CP plugin is lucky to have been made free and, although it is effective, it works, but it is not efficient if it changes the system all the time. I know they put everything they do in each update, I know and I realize, that's why I made this suggestion, that's why I made this recommendation, because I realized that the changes destroy everything that users do. It's not bad or a way to reproach it, it's a way of saying, hey, you're modifying things that break, whether it's spaces, changing one key for another, and then some actions modify the functionality of the panels and the Discord supports. I have no complaints or less with the staff or the devs. Don't look at this as a complaint saying "CommandPanels is horrible," no, that's an error. It's good, but at this point, it's not efficient, although it is effective. Maybe we, the configurators, like it, but the problem is that if they modify the panel file changing one or two or three characteristics, it becomes impossible and unsustainable for servers, whether they are free or premium. In essence, it's good to think that this is more like a warning to them not to modify too much in the syntax of panels to avoid future conflicts. As I say, it's not a threat or anything like that, it's a warning of what seems to be happening, and I'm seeing it. A hug.
