### ISSUE TITLE
Adding 1.16 HEX Support

### ISSUE THREAD

**Issue by kiloRs** [rockyhawk64/CommandPanels#32]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the solution you'd like
Simply, I just want to have the ability to use hex colors in all the mechanics of command panels.

**Comment by rockyhawk64** [comment]
What do you mean exactly by hex colours for the mechanics? There is RGB for leather armor but there isn't a whole lot of features that allow for custom colours.

**Comment by kiloRs** [comment]
All the text for lores ect

**Comment by rockyhawk64** [comment]
RGB does the same thing and if this is added it may be RGB colours appose to HEX.

**Comment by kiloRs** [comment]
Ah is there any limtations to it? What would the format be

**Comment by rockyhawk64** [comment]
Not really, if done it would probably be something like %cp-rgb-54-32-65%
https://www.rgbtohex.net/hextorgb/
You can convert one to the other.

**Comment by rockyhawk64** [comment]
Update:
It will be using HEX not RGB. so #fdde50 for example will be correct.

**Comment by rockyhawk64** [comment]
Done, you can use this in v3.7.0 by simply adding a hex in the name or lore.
