### ISSUE TITLE
add a command tag opposite to "hasperm="

### ISSUE THREAD

**Issue by RUYSUE** [rockyhawk64/CommandPanels#320]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

i gonna to set a permission shop that denies buy twice, but tags exist now dont support this.

### Describe the solution you'd like

add a command tag opposite to "hasperm=", like "hasnoperm=" which commands under will run only if player doesnt have the permission.

### Describe alternatives you've considered

i dont know

**Comment by TinyTank800** [comment]
https://github.com/rockyhawk64/CommandPanels/pull/321

Added in my pull request.

**Comment by rockyhawk64** [comment]
Now available on version [`3.21.4.0` ](https://github.com/rockyhawk64/CommandPanels/releases/tag/3.21.4.0)
