### ISSUE TITLE
Add support ItemsAdder

### ISSUE THREAD

**Issue by QuiquePineyro** [rockyhawk64/CommandPanels#34]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem? Please describe.
I have a plugin called ItemsAdder that add custom textures in items and I been trying to add theses items with custom texture in the panel of CommandPanles but it turns back the original texture when I save the panel

### Describe the solution you'd like
Make the plugin compatible with ItemsAdder to make my menus more attractive

**Comment by rockyhawk64** [comment]
Custom textures are currently done through custom model data

**Comment by QuiquePineyro** [comment]
I updated to the latest version and the plugin stills not saving the custom texture of my items

Proof: https://streamable.com/r4xwgv

**Comment by rockyhawk64** [comment]
If that is a custom model data item you need to shift-click the item inside of the editor and change it from there (it will be the button that looks like an anvil).
Dragging it in like that won't change it automatically. Dragging only works with regular items and with custom heads from Head Database Plugin.

Also keep in mind when dragging items, once you have manually added the custom model data code to an item inside of the editor, if you take it out of the inventory and back in, it will lose its commands and details, so once they are in there they can be swapped around but not taken out.

**Comment by fireFerry** [comment]
And I see you're on forge, if it's a forge server we don't offer support for that.

**Comment by rockyhawk64** [comment]
Forge is just compatible with Bukkit for the most part, so as long as the item is done using Custom Model Data and not custom items via Forge they will work, any items added into the game from Forge Mods will not work even while following my steps.

The reason why I assumed it was a Custom Model Data item is because of the extra NBT tag it has.

**Comment by QuiquePineyro** [comment]
Ohh I see, it works now using the shift-click, thank you very much @rockyhawk64 

And no, it's not a Forge server @fireFerry
