### ISSUE TITLE
Able to take items from gui and no commands triggered

### ISSUE THREAD

**Issue by MegloMania** [rockyhawk64/CommandPanels#35]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
When I open the gui, whether I'm opped, or not, I can move and take the items out of the gui, without them issuing the commands given in the config.

### Expected behavior
The item when clicked, to not move, and issue the command in the config, a recognised command with permissions given to the default group.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/68916505/88695473-deb41780-d0f9-11ea-99f4-f85556665fef.png)

### Versions:
 - Minecraft: 1.9
 - CommandPanels: 2.8.0

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.
https://pastebin.com/tAmtnj7i

**Comment by rockyhawk64** [comment]
https://www.spigotmc.org/resources/command-panels-classic-custom-guis.77182/
Use Commandpanels Classic here.

**Comment by MegloMania** [comment]
> https://www.spigotmc.org/resources/command-panels-classic-custom-guis.77182/
> Use Commandpanels Classic here.
> 
> Generally, v2.8.0 and older is for 1.13 Minecraft, they haven't been tested as much for older versions and some of the versions you were using may, in fact, be incompatible with Minecraft 1.9.

thank you! it now works
