### ISSUE TITLE
Balance Display

### ISSUE THREAD

**Issue by Cybrie** [rockyhawk64/CommandPanels#36]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
Hello I'm to Stupid to make a Panel that Display the Currently Money like in the Example I'm sorry :c

### Expected behavior
/

### Screenshots/videos
https://imgur.com/a/aZbuvgQ

### Versions:
 - Minecraft: [e.g. 1.16]
 - CommandPanels: [e.g. 3.7.1]

### Additional context/Panel files
/

**Comment by TheLonelyWolf1** [comment]
You can use %cp-player-balance% or any other Placeholder for that

**Comment by Cybrie** [comment]
Yes but how because when I write it like this 
 '8':
        material: GOLD_INGOT
        name: '&2Money'
        lore: %cp-player-balance%

Then it comes an error

**Comment by TheLonelyWolf1** [comment]
Try this: - '%cp-player-balance%'

**Comment by Cybrie** [comment]
Placeholder is advertised the money is not displayed :/

**Comment by fireFerry** [comment]
Can you send your panel file? And if you see errors in the console please send them too!

**Comment by Cybrie** [comment]
https://pastebin.com/TYjiprQq

Here how it is displayed:
https://imgur.com/a/W8qBANj

**Comment by Cybrie** [comment]
and when i write it like this

        lore:
        - %cp-player-balance% 

it cames: Error Found in config at: File with no panels found!

**Comment by fireFerry** [comment]
Are you on paperspigot or normal spigot?

**Comment by Cybrie** [comment]
normal Spigot

**Comment by fireFerry** [comment]
And when is the last time you ran BuildTools?

**Comment by Cybrie** [comment]
i have never used BuildTools :'D

**Comment by fireFerry** [comment]
Well if you are on normal Spigot you must have used BuildTools once to build your server

**Comment by fireFerry** [comment]
Or have got a set-up server from your host

**Comment by Cybrie** [comment]
i have a Hosted Server so i havent needed it yet xd

**Comment by fireFerry** [comment]
Well then please run it, it will update your server

**Comment by Cybrie** [comment]
I have on my server everything on the Latest version also Spigot when you that mean

**Comment by fireFerry** [comment]
BuildTools is a jar file that updates your server version, not your plugin versions. As 1.16 had a problem with lores in it's early state, you should use BuildTools to update your server version.

**Comment by Cybrie** [comment]
so yes i did it but it doesnt updates because i already had the latest version :'D

**Comment by fireFerry** [comment]
Okay, then do you see any errors in the console when opening the panel, with debug mode enabled? (/cpd)

**Comment by Cybrie** [comment]
This [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
and in the Chat: Error found in Config at Item: One of the Items does not fit in the Panel

**Comment by fireFerry** [comment]
I need the whole error, not 1 line.

**Comment by Cybrie** [comment]
But the error also comes without the balance section, everything still works.

**Comment by Cybrie** [comment]
If not, I will do it that you must click to show that in chat that is not a world problem for me :'D

**Comment by fireFerry** [comment]
Have you done /cpd?

**Comment by Cybrie** [comment]
Yes

**Comment by Cybrie** [comment]
you can see it on the Picture :'D

**Comment by fireFerry** [comment]
Have you checked all your materials? The error in chat says 1 isn't valid

**Comment by Cybrie** [comment]
So the Error is done[i had one Item Double in the Files] but the problem with the Balance is still there :/

**Comment by Cybrie** [comment]
But I'm going to do that with the click now because it really isn't that important

**Comment by Cybrie** [comment]
Thanks anyway have a nice day!

**Comment by fireFerry** [comment]
We'll still try to recreate the error but if we can't I'll keep it closed

**Comment by Cybrie** [comment]
okay thank you!
