### ISSUE TITLE
Item-on-join without stationary

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#37]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes/No
**Skipped because of Admin/Collaborator**

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes/No
**Skipped because of Admin/Collaborator**

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes/No
**Skipped because of Admin/Collaborator**

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when

**No it's not related to a problem.**

### Describe the solution you'd like

**I would like to see a feature so that you will get the open-with-item on join/spawn without using stationary, and that it just gets added in the first available hotbar slot. If the hotbar slots are full it will not be added.**

### Describe alternatives you've considered

**The same thing as above, but then it won't add to the first hotbar slot, but a selected one like stationary, but the item still being movable.**

### Additional context

**None.**

**Comment by rockyhawk64** [comment]
That can be done with /cp <pane name> item

**Comment by fireFerry** [comment]
But not automatically
