### ISSUE TITLE
Need help: How to add more pages to a GUI?

### ISSUE THREAD

**Issue by Endphoenix** [rockyhawk64/CommandPanels#38]
How can I add more pages to a GUI?

I want you to be able to add multiple pages to a GUI. Of course, the whole thing can be done by giving the "Next Page" item the command for the GUI, but how do I do that the next GUI can be opened by clicking on the item, but not by a command.

 - Minecraft: 1.14.4
 - CommandPanels: v3.6.0

**Comment by fireFerry** [comment]
Remove the command: section of the GUI's you don't want to open by command. And please don't delete the template for a next time, **It's created for a reason and for most cases we need it to help you further.**

**Comment by Endphoenix** [comment]
Ah, Ok, I didn't even know that. Thanks for the fast Support!

**Comment by fireFerry** [comment]
And just a tip, you should update to the latest version, 3.7.1

**Comment by Endphoenix** [comment]
Oh, Ok, what are the new features? Can I uptade from my current Version?

**Comment by fireFerry** [comment]
New features are listed [here](https://github.com/rockyhawk64/CommandPanels/releases/tag/3.7.2)

You can just replace the jar files when your server is offline.

**Comment by Endphoenix** [comment]
Ah, Ok. Thank you!

**Comment by fireFerry** [comment]
I meant 3.7.2, sorry for my typo.

**Comment by Endphoenix** [comment]
Nothing Matters.
