### ISSUE TITLE
Add PlayerPoints buy-command

### ISSUE THREAD

**Issue by CrazyMMG** [rockyhawk64/CommandPanels#41]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
**Yes**/No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
**Yes**/No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
**Yes**/No

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
I would greatly appreciate if you could add support for a buy-command for [PlayerPoints](https://dev.bukkit.org/projects/playerpoints). I really need this added, thanks.

### Describe alternatives you've considered

None.

**Comment by fireFerry** [comment]
This might gets added in the classic version, but not in the normal version of Command Panels.

**Comment by CrazyMMG** [comment]
Yeah the classic version is where i need it added.

**Comment by rockyhawk64** [comment]
Unfortunately, it is an old plugin and I will not be providing support for plugins that are not updated. I would strongly suggest finding a newer plugin, as that one has had an update last in 2016.
