### ISSUE TITLE
Request, Swap item for item (paywall-item=)

### ISSUE THREAD

**Issue by l0lm3n** [rockyhawk64/CommandPanels#43]
Dear Rockyhawk64,

is it possible to add an Item swap command in de future, 

the command needs to search a player’s inventory just like the Sell command, but instead of removing the first item and adding money they just remove the first item and add the requested item to the players inventory.

with this command the server admins has more control over the economy. 
they can make sure that dirt can be changed for grass blocks.
but not be sold for diamonds.

I hope me request is doable, and hope to hear from you.

Kind regards,
L0LM3N

Edit by Admin:
Please use the right template we made for feature requests. I don't know how you managed to create a blank issue, but please edit this issue with the feature request template.

fireFerry - Admin/Collaborator

**Comment by rockyhawk64** [comment]
Added.
