### ISSUE TITLE
[HELP] Mob Spawners

### ISSUE THREAD

**Issue by ChaoticWagon** [rockyhawk64/CommandPanels#45]
Have you checked the wiki page to see if the solution for your problem is there?
Yes

Have you checked the issue tracker to see if your issue is a duplicate and your problem already has been solved?
Yes

Have you asked for help in the Discord Server? (Or got redirected to a Github issue here)
No

Describe the Issue
A clear and concise description of what the problem is.

I Cant seem to make it so that people can buy mob spawners it says error config buy= 50 rabbit_spawner 1

Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

Versions:
Minecraft: 1.16.1
CommandPanels: 3.8.1
Additional context/Panel files
Add any other context about the problem here. Please also send you're panel in question. We only accept pastebin links.
[](https://pastebin.com/uM1DVvVK)

**Comment by fireFerry** [comment]
Please don't remove the template, we will not help you if you delete it.

**Comment by ChaoticWagon** [comment]
> Please don't remove the template, we will not help you if you delete it. You can edit your message and add the template

done

**Comment by fireFerry** [comment]
You can't use the buy= tag, as rabbit_spawner isn't a valid block. You will need to use buycommand= and then use the give command with spawnerdata.

**Comment by ChaoticWagon** [comment]
how would i take the spawner when they sell it

**Comment by fireFerry** [comment]
What do you mean? If they sell the spawner, it gives them money

**Comment by ChaoticWagon** [comment]
but dont you have to take the spawner away with a command

**Comment by fireFerry** [comment]
Yes, but you also need to do that with your economy plugin
