### ISSUE TITLE
'name' color not working in 'open-with-item' setting.

### ISSUE THREAD

**Issue by charlesthms** [rockyhawk64/CommandPanels#46]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
When I'm trying to change the colour of the name in the setting called "open-with-item" the colours in game are not showing up properly, I just see the colours tag. (example of what appears in game : &6[&fhello&6])
### Expected behavior
The name should appears with colours and not with those weird tags.

### Screenshots/videos
![image](https://user-images.githubusercontent.com/65021094/90181764-3ec0e400-ddb1-11ea-8d6a-4559cda7e34e.png)

### Versions:
 - Minecraft: 1.16.1 (I also tried in 1.16.2)
 - CommandPanels: 3.8.3

### Additional context/Panel files
The file is the example.yml generated by default with the plugin, if I don't touch anything at the first start I have the clock coloured like that 
![image](https://user-images.githubusercontent.com/65021094/90182188-dc1c1800-ddb1-11ea-92e8-3d105a72bacf.png)
But if I change one character it won't work even if I restore the original file, the only way is desinstall/reinstall the plugin.
My server is on spigot with essentialX chat.

**Comment by rockyhawk64** [comment]
Can you send the panel file for the panel that is not working with the colours? I cannot replicate this using those steps. What are you doing exactly in order to make that happen? Also, ensure you have the latest version of 1.16.1 spigot or paper.

**Comment by charlesthms** [comment]
Panel file : https://pastebin.com/ntgShY4R

Ok what I do to make it happens is to change at line 18 &6 by &4. This change is not working but when I restore my change (replacing &4 by &6) It doesn't work either while the display was correct at the beginning.
I made a fresh install of spigot 1.16.1 with BuildTool.

**Comment by rockyhawk64** [comment]
Which version of spigot or paper are you running? I am using paper-135 (latest) with no issues.
Also, can you list out the plugins you are using, maybe another plugin could be causing the issue.

**Comment by charlesthms** [comment]
I tried with paper-135 and essentialX, it still doesn't work

**Comment by rockyhawk64** [comment]
Try the new update 3.9.0 for CommandPanels that was just released.
https://www.spigotmc.org/resources/command-panels-custom-guis.67788/
Seemed to only be a bug when placeholder API was not installed on the server.

**Comment by charlesthms** [comment]
It's working !!

**Comment by charlesthms** [comment]
Thank you for the support !

**Comment by rockyhawk64** [comment]
No problem.
