### ISSUE TITLE
Suggestion: Webpage

### ISSUE THREAD

**Issue by normotory** [rockyhawk64/CommandPanels#47]
I believe there should be a web page, this will have a menu and such where you can click on a slot and type what item you want. You can then modify it using a dropdown menu of what you want and so on. Basically a generator for the panels. Once you are done you click generate and it asks you for the name of the panel. You insert it and it gives you a panel file to replace the old one.

**Comment by fireFerry** [comment]
Nice Idea, but we made a template for feature requests. Please edit your message and apply the following [template](https://github.com/rockyhawk64/CommandPanels/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=). Issues without a templates will not be further replied to.
