### ISSUE TITLE
Readd player skin heads things.

### ISSUE THREAD

**Issue by intorsetorpolice1intorsetoprolice** [rockyhawk64/CommandPanels#48]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes/[No]

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes/[No]

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes/[No]

### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
NO
### Describe alternatives you've considered
MO
### Additional context
NO

**Comment by fireFerry** [comment]
Closed because not taken seriously.
