### ISSUE TITLE
Register command for panel for tab completion.

### ISSUE THREAD

**Issue by Rend-Creator** [rockyhawk64/CommandPanels#5]
**Is your feature request related to a problem? Please describe.**
There's not much of a problem, its just a feature that will give the plugin a little feature. Since 1.14+ needs to recognized a registered command. Thus if the command is not recognized, it throws an error saying the command is non existing. Well this will help for servers for aesthetic purposes.

**Describe the solution you'd like**
Add a option to register the command for the panel. By this, it will appear on the tab complete.

**Describe alternatives you've considered**
No info

**Additional context**
Nothing much. Just a request for a feature.

**Comment by rockyhawk64** [comment]
The 'commands:' feature in the plugin indeed does not appear to be recognized in 1.14+ versions. There is an alternate method that needs to be used.
In the root folder of your server (not part of the plugin), there is a file called 'commands.yml. This file can be used to create custom commands which is what you will have to use instead. In the aliases section, you will need to put the /cp command used to open the panel and make it open any other command.

For example, if you have a panel that is named 'panel-3' and you want the command to be /workbench, do this:
```
aliases:
  workbench:
  - cp panel-3
```
Remember for this file, you will need to restart/reload the server for changes to take effect.

**Comment by Rend-Creator** [comment]
Oh nice thanks! Didn't know its purpose until now :D
