### ISSUE TITLE
How to put in online players for other bungee servers

### ISSUE THREAD

**Issue by Spooonnn** [rockyhawk64/CommandPanels#52]
I have multiple bungee servers, what is the parameter to display how many people are online in each server, I know I use something like %cp-online-players%, but it only displays me when theyre are other people online on others servers

**Comment by TheLonelyWolf1** [comment]
So...the placeholder works but only shows the players of the other servers of the network.

Do you have PlaceholderAPI activated? Then you could use the Bungee-Extension instead.

**Comment by Spooonnn** [comment]
I have placeholder api installed and working, the problem is if im on my creative server, and im using the gui to look and see howw many players are on another server using %cp-online-players%, it displays the same number as creative
do i need to put the server same somewhere in %cp-online-players%

**Comment by Spooonnn** [comment]
how would i get those again lol

**Comment by TheLonelyWolf1** [comment]
I have the assumption, that %cp-online-players% only shows the players of the server it is used on and not the whole Network

**Comment by Spooonnn** [comment]
ya that sounds about right, anyway it uses the network then?

**Comment by TheLonelyWolf1** [comment]
> how would i get those again lol

get what?

> ya that sounds about right, anyway it uses the network then?

What should use the network? I don't quite understand what you're talking about now

**Comment by Spooonnn** [comment]
%cp-online-players% is only counting my creative server, and reading as 1 player online on that serverr, which is correct, but on all my other servers its reading 1 player online, which is incorrect, how can I correct that, so it actually reads the other servers and not saying 1 player online on each server

**Comment by TheLonelyWolf1** [comment]
> but on all my other servers its reading 1 player online, which is incorrect
How many Players are online on the other servers?

**Comment by fireFerry** [comment]
@TheLonelyWolf1 he was talking about the papi placeholders.

@Spooonnn do the following steps please:
1. Install papi and cp on all servers.
2. Make sure all servers have the bungeecord extension, by doing `/papi ecloud download Bungee`
3. You can now use the following placeholders:

![Screenshot_20200825-175458.png](https://user-images.githubusercontent.com/61279925/91197887-29767e80-e6fc-11ea-80a1-b2ee81f1655a.png)

Please reply if it works

**Comment by Spooonnn** [comment]
that works thanks!
