### ISSUE TITLE
/cpe deleting content in panel.yml files

### ISSUE THREAD

**Issue by TinyTank800** [rockyhawk64/CommandPanels#53]
I have had a few instances where i change the yml file to add HasPerm's or lore's and saving it then reloading and opening the panel. Everything is correct but after, i then do /cpe to add or change an item(drag and drop then close out to save) it then delete's some of the lore's or hasperm sections.

if you have any questions msg me on discord. im in your server or TinyTank800#8794 i respond much faster there i can also call.

**Comment by rockyhawk64** [comment]
If you move items around in the editor while they have sections like hasperm there is no 100% guarantee that they will be carried over. In particular, if you place those items into your inventory, and then back into the editor they will lose their values.

**Comment by TinyTank800** [comment]
ok i just tested and realized its just me being dumb. i forgot to do the hasperm0 and hasperm1 so both were hasperm and editing just deleted one of them. :D
