### ISSUE TITLE
Feature that allows you to make GUI's faster

### ISSUE THREAD

**Issue by Endphoenix** [rockyhawk64/CommandPanels#55]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Is your feature request related to a problem? Please describe.
It is always very difficult to change the name to an empty name for all glass panes.

### Describe the solution you'd like
Adds two new options for the Panel Configs:

1. All fill items automatically have an empty name.

2. All glass panes automatically have an empty name.

### Describe alternatives you've considered
/

**Comment by fireFerry** [comment]
You can do that very easy using the editor, if you first rename the glass panes to nothing, and then place them in it will work.

**Comment by Endphoenix** [comment]
So I have to do all my panels new?

**Comment by fireFerry** [comment]
No, not really, if they all have the name like Black Stained Glass Pane, you could replace them all by once

**Comment by Endphoenix** [comment]
How?

**Comment by fireFerry** [comment]
If you're using notepad++, and if you're on windows you can use ctrl + F and go to the replace tab and choose what to replace and then replace all.

**Comment by Endphoenix** [comment]
But with what?

**Comment by fireFerry** [comment]
With `name: ''`

**Comment by Endphoenix** [comment]
This is already the case on all my panels, but it still shows "Black_stained_glass_pane", when I hover it.

**Comment by fireFerry** [comment]
If the name is just a space or nothing it shouldn't say something

**Comment by rockyhawk64** [comment]
The name for empty items should be '&f'
