### ISSUE TITLE
buycommand not executing in console

### ISSUE THREAD

**Issue by FlirtyMomma** [rockyhawk64/CommandPanels#58]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
The buycommand tag isn't executing in the console since the latest update. It appears to be executing as a player command.

### To Reproduce
1. Create a GUI using a buycommand tag.
2. Use the GUI with sufficient funds and as a person with no permission to run the command normally
3. Money should have been taken with no command run

### Expected behavior
Command to execute in the console.

### Versions:
 - Minecraft: 1.16.2
 - CommandPanels: 3.10.3

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by ArvickC** [comment]
Can you post your panel please? Use [Pastebin](https://pastebin.com/)

**Comment by FlirtyMomma** [comment]
https://pastebin.com/K3G4jCdw

There's the panel, but this worked on a previous version.

**Comment by FlirtyMomma** [comment]
https://pastebin.com/K3G4jCdw

There's the panel, but this worked on a previous version.

**Comment by ArvickC** [comment]
Do you get any error message? (Check in-game and console)

**Comment by ArvickC** [comment]
Aha! You need to put an output to all the hasperm!

**Comment by FlirtyMomma** [comment]
What do you mean?

**Comment by ArvickC** [comment]
hasperm:
          perm: fabledskyblock.generator.third
          output: <true/false>
          material: ORANGE_CONCRETE
          name: §9Level 3 - $10k
          enchanted: 'true'
          lore:
          - §7§l->-->>-----<<--<-
          - '§7§lUNLOCKED: §a§lYES'
          - §7§l->-->>-----<<--<-

**Comment by FlirtyMomma** [comment]
Ok. I've found it on the wiki, but I don't really understand what it means?

**Comment by FlirtyMomma** [comment]
Wait, it's just used it it has the permission or not? Isn't that the point in the Hasperm in the first place?

**Comment by ArvickC** [comment]
So say the perm: fabledskyblock.generator.third, if the output is set to true, it checks if the output of fabledskyblock.generator.third is true, then it enters the hasperm

**Comment by FlirtyMomma** [comment]
So, to have it work how it was working before, I should just put them all as true?

**Comment by ArvickC** [comment]
Yeah

**Comment by FlirtyMomma** [comment]
Okay. Thanks for the quick response 👍

**Comment by ArvickC** [comment]
No Problemo 👍

**Comment by ArvickC** [comment]
Btw the latest version isn't 3.2.3

**Comment by FlirtyMomma** [comment]
Sorry, put the wrong number. I meant 3.10.3

**Comment by FlirtyMomma** [comment]
Umm... I added the output thing to my first panel, but I'm still getting the same thing

**Comment by ArvickC** [comment]
Do you get any error message? (Check in-game and console)

**Comment by FlirtyMomma** [comment]
Still no issue in the command. Everything is doing the exact same thing. The panel is opened, the money is taken, and this message is sent:

![image](https://user-images.githubusercontent.com/9404733/91891252-9c49a180-ec88-11ea-9c98-cf7c2f6fd2c0.png)

This message is only normally sent if a player tried to run a luckperm command

**Comment by ArvickC** [comment]
And the problem is the player doesn't get the perm?

**Comment by FlirtyMomma** [comment]
Yes. They're supposed to buy the permission which gives them an upgrade.

**Comment by ArvickC** [comment]
And is it all of them that aren't working or just a few?

**Comment by FlirtyMomma** [comment]
All of them have the same issue. I even have a second panel that is having the same problem (Also updated with the output).

**Comment by ArvickC** [comment]
Try this for all of them:

    item:
      '0':
        material: RED_CONCRETE
        name: §9Level 2 - $5k
        commands:
        - buycommand= 5000 console= lp user %cp-player-name% permission set fabledskyblock.generator.second
        hasperm:
          perm: fabledskyblock.generator.second
          material: RED_CONCRETE
          name: §9Level 2 - $5k
          enchanted: 'true'
          lore:
          - §7§l->-->>-----<<--<-
          - '§7§lUNLOCKED: §a§lYES'
          - §7§l->-->>-----<<--<-
          commands:
          - msg= &eYou've already unlocked this!

**Comment by FlirtyMomma** [comment]
That fixed it. Thank you 👍

**Comment by FlirtyMomma** [comment]
But I suppose it's still a bug, as it's meant to always use the console?

**Comment by ArvickC** [comment]
:D

**Comment by TinyTank800** [comment]
the console= made it so it will go through console for the lp command so its not trying to run through player since they wont have perms

**Comment by ArvickC** [comment]
> But I suppose it's still a bug, as it's meant to always use the console?

CP is design to have player used first or as default

**Comment by FlirtyMomma** [comment]
The wiki (and previous versions) used the console for the buycommand

**Comment by FlirtyMomma** [comment]
It's also pointless for a player to buy a command they already have access to.

**Comment by FlirtyMomma** [comment]
Nevermind, I can't change it to a bug. Unless you don't think it is?

**Comment by ArvickC** [comment]
Hmmm yeah, thanks for letting us know, I'll contact the dev and let them know!

**Comment by fireFerry** [comment]
It's not a bug, just wrong info on the wiki. #59 is the issue for that.

**Comment by FlirtyMomma** [comment]
A little bit pointless without adding the console to it... But okay...
