### ISSUE TITLE
Command Tag buycommand in wiki

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#59]
Hello,

In the wiki is stated the following:

buycommand=
Player will buy a command. Usage: "buycommand= [price] [command]"
The commands are executed in console, like this as an example for players names: "buycommand= 100 gamemode creative %cp-player-name%"

But the commands aren't actually executed in the console, could you change that rocky?

**Comment by rockyhawk64** [comment]
buycommand= <price> console= <command>
for console.
