### ISSUE TITLE
missing class

### ISSUE THREAD

**Issue by Lucifer187** [rockyhawk64/CommandPanels#60]
Now with commands I can open the panel, opening a panel with an item is not possible, according to the console the class.openWithItem seems to have been forgotten (this is the cp for spigot 1.8.8), this class is missing in both the 1.12.0, as well as 1.12.1:

[01:26:29 ERROR]: [CommandPanels] Plugin CommandPanels v2.12.0-classic has failed to register events for class me.rockyhawk.commandPanelsClassic.openWithItem.utilsOpenWithItem because org / bukkit / event / player / PlayerSwapHandItemsEvent does not exist.

**Comment by rockyhawk64** [comment]
This is not a bug. The reason it is not registered is that Minecraft 1.8 doesn't have the feature that allows you to place items in both of your hands, hence why it is "PlayerSwapHandItemsEvent".

**Comment by Lucifer187** [comment]
With the 2.10.0 I could also open the panel with the items until I updated, I'm confused

**Comment by Lucifer187** [comment]
Bungeecord-Hilfe ( /hilfe ) : https://pastebin.com/7Ua3Aesj

Lobby-compass: https://pastebin.com/V6zbMKaE

(spigot 1.8.8) Command Panels Classic v2.10.0. :

with / help you can open the panel, this brings you to a help list - [click] on the item and you get to which commands I can carry out - now you are at the commands that every player can carry out and from there you will get this error message in the console: https://pastebin.com/bzSUZ3X2.
In this case, the compass teleporter or a settings panel can no longer be opened, no error is displayed in the console or in the chat (an example panel can be opened again)

if you search for / cp citybuild-panel, for example, you get this message in the console: https://pastebin.com/6NLETrTr and a panel is not opened and in the chat it is written that this panel would not exist

it was possible to click the itembar

(spigot 1.8.8) Command Panels Classic v2.12.0. :
When the server is finished loading, this message appears https://pastebin.com/XR9VZtMG

with / help you can open the panel, this brings you to a help list - [click] on the item and you get to which commands can i execute - now you are with the commands that every player can carry out - now you are with the player commands, there you will find friends, party and clan commands, all of which can be opened.

the panel can also be opened with the example command / cp citybuild-panel

clicking on an item in the item bar is not possible, and no message appears in the console or in the chat.

(spigot 1.8.8) Command Panels Classic v2.12.1. :
same problem see: (spigot 1.8.8) Command Panels Classic v2.12.1.

**Comment by rockyhawk64** [comment]
![Capture](https://user-images.githubusercontent.com/18727981/92048925-3b2ae680-edcc-11ea-9aac-c568d5162c85.PNG)
These errors look like they are from PlaceholderAPI, not my plugin. Have you updated your PlaceholderAPI plugin? It should be version 2.10.9 as that is the latest.

**Comment by Lucifer187** [comment]
the placeholderapi has been updated, the only thing that was missing was vault. I have now fixed this, but now there is still the problem that I would like to have the openwithitem again, which is no longer possible on version 1.8.8

**Comment by fireFerry** [comment]
It is still possible, it will likely only display a little error at startup about the sawphands class.

**Comment by rockyhawk64** [comment]
I will have to fix the Hotbar items

**Comment by Lucifer187** [comment]
thx

**Comment by rockyhawk64** [comment]
kk the latest version now, 2.12.2 should fix that issue.

**Comment by Lucifer187** [comment]
ok, now the item hotbar works as usual, some items are not properly recognized (for example REDSTONE_COMPARATOR in the hotbar), but that's ok
