### ISSUE TITLE
The Example panel is always showing up im my 5th slot in my hotbar even though i deleted the example panel

### ISSUE THREAD

**Issue by stephenblackbook** [rockyhawk64/CommandPanels#61]
i have no idea what to do, when i try deleting it it says that its already deleted

**Comment by rockyhawk64** [comment]
To ensure the panel is deleted try to follow these steps:
1. Remove the example.yml from the panels folder
2. Type /cpr into the game
3. If there are no other panels in the panels folder, the example panel will reappear
4. Type /clear, or delete the old example panel item.

**Comment by stephenblackbook** [comment]
Thank you I figured it out ☺️
