### ISSUE TITLE
Refresh command/tag

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#62]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
**Yes**/No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
**Yes**/No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
**Yes**/No

### Is your feature request related to a problem? Please describe.

**It isn't really related to a problem, more something that would be handy**

### Describe the solution you'd like

**I would like that you could use commandpanelrefresh under the commands in an item or something similar to that, so that when you click the item it refreshes the panel if the command is there.**

**Comment by rockyhawk64** [comment]
the exact same thing can be done with this though
redirect:
  panel: <the panel>
  force: true

**Comment by fireFerry** [comment]
And I can use open=, didn't realize xD
