### ISSUE TITLE
Panels becomes buggy with RGB Title

### ISSUE THREAD

**Issue by CroaBeast** [rockyhawk64/CommandPanels#63]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
The bug is in the video that I adjunt in this report.

### To Reproduce
1. Create a new panel with all the default config.
2. Edit the title and add a RGB color.
3. Save the config files.
4. Go to your server and use /cpr.
5. Use the command of your panel.
6. Try to drag any item in the panel and wait for a new item in the panel appears. (See video)
7. Profit.

### Expected behavior
Not duplicate items,

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
[Action 5-09-2020 15-02-58.zip](https://github.com/rockyhawk64/CommandPanels/files/5178594/Action.5-09-2020.15-02-58.zip)
If the file doesn't work, try this link of the message in the discord group: https://discordapp.com/channels/602338405883314206/602338405887508480/751895264687685644

### Versions:
 - Paper 1.16.2
 - CommandPanels 3.10.4

### Additional context/Panel files
None

**Comment by rockyhawk64** [comment]
Can you attach the panel that you used in the video? All of the panels that I have in my test server have colours in the title with no issues.

**Comment by CroaBeast** [comment]
`stars:
    perm: default
    rows: 5
    title: '#660000&l¡Todas tus estrellas! ⭐'
    command: stars
    sound-on-open: BLOCK_NOTE_BLOCK_CHIME
    empty: WHITE_STAINED_GLASS_PANE
    item:
      '12':
        material: PAINTING
        name: '#8EBFF7&mEstrella Bloqueada'
        lore:
        - '#BCAC80Nivel Requerido: #C3D8DF&l50'
        hasperm:
          perm: star.1
          output: true
          material: cps= eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWE0YjBlYWY1MjY5YTM0ZTI3OGNhZThiYzVjNmNiMTEyMDIzNDRhOTRiZDhmNGE3OWFlNmI4MTJjZDZjZmYifX19
          name: '#F6E383&l&nEstrella Obtenida&r &7&l⭐'
          lore:
          - '#BCAC80Tier: #99FFFF&lI #B4C9C9[Tienda Básica]'
          - '#BCAC80Mostrando en chat: #A94242&lNO ❌'
          - '#8FE969Click aquí para mostrar.'
          commands:
          - 'console= lp user %cp-player-name% meta setsuffix 1 " &7&l⭐"'
          - 'console= lp user %cp-player-name% meta set star 1'
          hasvalue:
            compare: '%luckperms_meta_star%'
            value: 1
            output: true
            material: cps= eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWE0YjBlYWY1MjY5YTM0ZTI3OGNhZThiYzVjNmNiMTEyMDIzNDRhOTRiZDhmNGE3OWFlNmI4MTJjZDZjZmYifX19
            name: '#F6E383&l&nEstrella Obtenida&r &7&l⭐'
            lore:
            - '#BCAC80Tier: #99FFFF&lI #B4C9C9[Tienda Básica]'
            - '#BCAC80Mostrando en chat: #8FE969&lSI ✔'`

**Comment by rockyhawk64** [comment]
v3.10.5 (Done)
