### ISSUE TITLE
Adding place holder ability to title of panel

### ISSUE THREAD

**Issue by Nieblue** [rockyhawk64/CommandPanels#65]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
The panels work great until I add a placeholder to the title ex: title: Mwatch 1.0 %cp-player-displayname%  it works for a little bit then the panel breaks and it is unusable till the place holder is removed.

### Describe the solution you'd like
Allow placeholders in the title option of the panel.  It is a cool feature that would allow additional personalization to the players.

### Describe alternatives you've considered
Allow for a title screen to display in front of the GUI instead of behind it.  I can make a title display when opened, but it is always behind the GUI.

### Additional context
![2020-10-02_08 01 09](https://user-images.githubusercontent.com/71209649/94927948-94983b00-0488-11eb-9c64-72bf261dd3ee.png)
![2020-10-02_08 24 46](https://user-images.githubusercontent.com/71209649/94928185-e80a8900-0488-11eb-916b-8ad419c28c97.png)

**Comment by fireFerry** [comment]
Minecraft has no possibility to have titles in front of GUI's, if you display a title and open your inventory, you will see the inventory will be in front. Placeholders in titles were added before, but they lagged the panels very much.

**Comment by rockyhawk64** [comment]
Releasing next update.
