### ISSUE TITLE
Execute command on opening a panel via hotbar item

### ISSUE THREAD

**Issue by mani00132** [rockyhawk64/CommandPanels#66]
Is it somehow possible to execute a command on opening a panel via the hotbar item? If not, please implement this.

**Comment by fireFerry** [comment]
Hello, It looks like you haven't used the template, please do next time, it helps us a lot! You can use commands-on-open if you want commands for when you open a panel!

**Comment by mani00132** [comment]
I am sry for not using the template, but is it possible to check whether the player is in the XY world, when you open the panel and if he does so, only then execute a command?

**Comment by fireFerry** [comment]
no, hasperm and hasvalue can not be added in commands-on-open.

**Comment by mani00132** [comment]
so then how would you solve it?

**Comment by fireFerry** [comment]
It isn't currently possible
