### ISSUE TITLE
List of suggestions for the Command Panels Server

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#70]
This template is used to suggest things to be added to the **Command Panels Server**, if you would like to suggest something for the **Command Panels Plugin**, click [here](https://github.com/rockyhawk64/CommandPanels/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=)

### Describe the solution you'd like
the following suggestions are all suggested by other players or me.
- Discord and Minecraft chat synced, DiscordSRV
- Harbor or /voteskip night, to skip the night if x people are sleeping/used the command.
- Dynmap to see a map of the server on a website.
- Chestshops, so players can easily buy stuff from another.

**Comment by rockyhawk64** [comment]
https://commandpanels.org/forums/suggestions.11/
