### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by SavagePanda116** [rockyhawk64/CommandPanels#72]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
I'm receiving errors in my console whenever a player joins the server or teleports to a different world on the server (like our separate spawn world).
Here is the error when a player joins: https://pastebin.com/8ZhqGVbn
Here is the error when a player teleports between worlds: https://pastebin.com/tusxQdcJ

### Versions:
 - Minecraft: 1.16.3
 - CommandPanels: 3.12.3

### Additional context/Panel files
I just added this plugin last night and have not changed anything in the config.

**Comment by fireFerry** [comment]
Please remove the open-with-item section from the example panel and try again.

**Comment by rockyhawk64** [comment]
You'll have to send your panels, the error is coming from one of them.

**Comment by SavagePanda116** [comment]
> Please remove the open-with-item section from the example panel and try again.

That did it! Thank you :)

**Comment by SavagePanda116** [comment]
> You'll have to send your panels, the error is coming from one of them.

Possibly because I made the "stationary" option in the open-with-item section just as '' to get rid of it. Removing the whole section removed the errors.
