### ISSUE TITLE
example.yml error upon loading (v3.12.5)

### ISSUE THREAD

**Issue by rockyhawk64** [rockyhawk64/CommandPanels#74]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
example.yml file fails to load correctly and gives a syntax error in console

### To Reproduce
1. Delete panels folder
2. Run server with command panels installed

### Versions:
 - Minecraft: All
 - CommandPanels: 3.12.5

**Comment by TinyTank800** [comment]
Lol I love the reproduce section :) fun bug

**Comment by ArvickC** [comment]
hehe
