### ISSUE TITLE
Between values

### ISSUE THREAD

**Issue by Danrique** [rockyhawk64/CommandPanels#75]
Well what I will ask is a little more specific but I say that you already made something in "hasperm". The example may speak a little better:

      '28':
        material: IRON_SWORD
        name: §6Troca de Gênero
        lore:
        - §bYou have LESS THAN $500
        commands:
        - 'msg= You have $600+!'
        hasgreater0:
          output: true
          value: 600
          compare: '%cp-player-balance%'
          material: RED_WOOL
          name: '&aYou have MORE THAN $600'
          commands:
          - 'msg= You have $600+!'
        hasgreater:
          output: true
          value: 500
          compare: '%cp-player-balance%'
          material: LIME_WOOL
          name: '&aYou have $500'
          commands:
          - 'msg= You have $500!'

So, if the guy has less than 500 a sword should appears, if the guy has more than 500 but less than 600 a Lime wool should appear, finally if the guy has more than 600 a red wool will appear.

I want to make a panel for ppl join the duel arenas, each arena will have a rating that is given by a placeholder. I want to make the button "clicable" only if you are in the range of the rating. I know, a little specific and I will understand if you dont want to.

Anyway, thanks for the amazing plugin!

**Comment by TinyTank800** [comment]
Thats how has greater works. You got it exactly. So doing what you are saying should work. If you want help making it or have questions on it while making it you can ask on the discord. Lots of fast responses and people to help you :).
