### ISSUE TITLE
Spawns Items in different worlds

### ISSUE THREAD

**Issue by DrogonBlue** [rockyhawk64/CommandPanels#76]
So I seted up a Lobby, in the hotbar the player spawns with 3 items, example panel, GameMode panel and profile panel, In the GameMode panel when I click an Icon it Teleports me using /mvtp ( aka Multiverse core ), I am also using Multiverse Inventory, for items, the problem is that when I am teleporting to that other world Command Pannel still spawns AND replace the previous items from the hotbar.

I may like another config file, And choose where and what Custom Panels ( items ) to give to player. thanks in advance.

**Comment by DrogonBlue** [comment]
Yes I put the Lobby and That world in different Inventory groups. The Items are saving correctly, for separate worlds. I also tried to remove those items when entring, but it still leads to items lose, from the step when Menu Panel Items replace old ones.

**Comment by fireFerry** [comment]
Hello! You will need to add the `disabled-worlds` tag to each panel to disable the item in specific worlds, more info [here](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/placeholders-and-panel-editing)

**Comment by DrogonBlue** [comment]
oh, now I see, sorry for my non-Informed properly  me, I made a mistake not reading the hole paper, although it was easier in this way, I suppose, such a great comunity. Sorry for bothering.
