### ISSUE TITLE
Command sequences not working.

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#77]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
Command panel sequences are not working at the moment, tried the wiki example as well

### To Reproduce
1. create a command sequence
2. use the sequence= tag
3. it doesn't execute the commands

### Expected behavior
It should execute the commands defined in the sequence

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: 1.16.4
 - CommandPanels: 3.13.1.1

**Comment by rockyhawk64** [comment]
Fixed the wiki example, the sequences now work like this:
before:
`- sequence= panel.example.exampleSequence`
after:
`- sequence= exampleSequence`

**Comment by fireFerry** [comment]
Thanks, didn't know that was the issue!
