### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by RickyLaChow** [rockyhawk64/CommandPanels#78]
I have this error in console https://pastebin.com/YuFzLBXn

### Versions:
 - Minecraft: [1.16.4]
 - CommandPanels: [3.14.0.0]

**Comment by fireFerry** [comment]
Hello! Because you didn't use the template, we don't have the information needed! Please edit your message with the template. If you don't the issue will be closed in 48h.

**Comment by RickyLaChow** [comment]
Nothing, i think is a problem with Gcore.
