### ISSUE TITLE
Autocompleting Commands in the Minecraft Chat Menu

### ISSUE THREAD

**Issue by Armagedon711** [rockyhawk64/CommandPanels#80]
_This Suggestion is to do with Creation of custom commands for Command Panels Minecraft versions 1.13 and up._

**Have you checked the wiki page to see if your suggestion is already added?
Yes

Have you checked the issue tracker to see if your suggestion was already submitted and denied?
Yes

Have you asked if the feature already exists in the Discord Server? (Or got redirected to a Github issue here)
Yes**

**Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

It isn't really related to a problem, more something that would be handy

**Describe the solution you'd like
A clear and concise description of what you want to happen.**

Since Minecraft 1.13 you can autocomplete commands in the Minecraft chat menu it will also show all available commands. When setting commands custom commands for panels, these Minecraft  Completions are not shown, they also show red indicating to all users that the command is not available. It would be nice if the custom commands for panels would show here instead of turning red so users know that it is a valid command.

**Describe alternatives you've considered**
There are no alternatives for this issue.

Additional context
![Immage1](https://user-images.githubusercontent.com/75109551/100416374-4fd5ee00-304c-11eb-9c51-274dcc20f0f9.png)
![cxzzxc](https://user-images.githubusercontent.com/75109551/100416573-d25ead80-304c-11eb-874b-41af05fc8aff.png)

**Comment by rockyhawk64** [comment]
The only alternative currently is to use the commands.yml file in the root of your server.
If for example the panel name is panel-4, this is what you would add to the commands.yml (to make the /worlds command):
```
worlds:
- cp panel-4
```
https://bukkit.gamepedia.com/Commands.yml
