### ISSUE TITLE
Split up bought/sold messages in config into money/token so that one can edit the messages separately

### ISSUE THREAD

**Issue by DrakePork** [rockyhawk64/CommandPanels#81]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Yeah that the token and money payment methods both use the same bought/sold message, and I would like to change it so that the two are different.

### Describe the solution you'd like
Change:
    needmoney: '&cInsufficient Funds!'
    bought: '&aSuccessfully Bought For $%cp-args%'
    sold: '&aSuccessfully Sold Item!'
into:
    needmoney: '&cInsufficient Funds!'
    bought: '&aSuccessfully Bought For $%cp-args%'
    sold: '&aSuccessfully Sold Item!'
    token-bought: '&aSuccessfully Bought For $%cp-args%'
    token-sold: '&aSuccessfully Sold Item!'
    token-needmoney :'&cInsufficient Funds!'

### Describe alternatives you've considered
The only alternative I see here would be for me to build the plugin myself and then change it.

**Comment by rockyhawk64** [comment]
If you set the message in the config to empty like this:
`bought: ''`
then it will not send a message, then you can set a custom message for anything like this:
```
commands:
- 'buy= 1 STONE 1'
- 'msg= %cp-tag%&aSuccessfully Bought Item!'
```
