### ISSUE TITLE
Panels is not openning by command

### ISSUE THREAD

**Issue by Zdoolny** [rockyhawk64/CommandPanels#82]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes/

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
After the update the latest update my panels it's not openning by command set in panel config. For example: panel "help-panel" have a line "command: help menu pomoc m" in config, after to try to use command /menu or /help server responding me: Undefined command. Use /help to... Before the update it's working OK. 

### Expected behavior
I want to make it works again.

### Screenshots/videos
Not needed.

### Versions:
 - Minecraft: 1.16.3
 - CommandPanels: 3.14.1.0

### Additional context/Panel files
https://pastebin.com/3atB1qfY

**Comment by fireFerry** [comment]
You have not asked in the Discord server, nor you have looked at the update logs or the wiki. It must be setup like this now:
![image](https://user-images.githubusercontent.com/61279925/101073930-75a94880-35a0-11eb-9152-a6c72895c2cc.png)

**Comment by Zdoolny** [comment]
Thanks and sorry for not getting acquainted for updates and Discord info.
