### ISSUE TITLE
When you rename a panel you can no longer access it via the /cp command

### ISSUE THREAD

**Issue by tazzanmc** [rockyhawk64/CommandPanels#87]
When I change the name of a panel (pictured in the attached image) from something other than panel-# the /cp command no longer recognizes it as a panel. This goes for panels that have also had their file name changed and for ones that haven't. Is there a fix available?
![Screen Shot 2020-12-14 at 1 31 31 PM](https://user-images.githubusercontent.com/35785712/102120722-f07c2a00-3e10-11eb-99ed-5cbe5eec970a.png)

**Comment by fireFerry** [comment]
Please use the template provided to help you. What cp version are you using? (template question)

**Comment by rockyhawk64** [comment]
You need to do /cpr to reload the plugin after changing panels.
