### ISSUE TITLE
Support "&" for color codes

### ISSUE THREAD

**Issue by KickSquareMC** [rockyhawk64/CommandPanels#88]
Hi, not sure if this is for all color codes, but for example when adding lore to an item, only the "§" symbol works, not the "&". For example: `§ctest` would work, but `&ctest` would not.

**Comment by fireFerry** [comment]
This has already been a thing for a very long time, are you sure you are using the latest version?

**Comment by KickSquareMC** [comment]
I'm using CommandPanels v3.11.2

**Comment by fireFerry** [comment]
ooh, then you should definitely update

**Comment by KickSquareMC** [comment]
Also, I'm pretty sure it works for most other parts. Not the lore though

**Comment by fireFerry** [comment]
also do know that color codes do not get parsed in /cpe, this is intentionally.

**Comment by KickSquareMC** [comment]
Got it. I'll update now, thanks for the super quick reply.

**Comment by fireFerry** [comment]
Under a minute lol
