### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by KickSquareMC** [rockyhawk64/CommandPanels#89]
Hi! Sorry to bother you again but I have another question. 

Basically, I made an upgrade menu where players can upgrade their tools with better enchantments. For example, they can click a button that says "Upgrade to Efficiency 5, Cost $5000" which will enchant the tool they are holding with Efficiency 5 for $5000. While I can just do run the `/enchant` console command, that would enchant any item they are holding, even stone for example. Would it be possible to do something along the lines of `enchantment= efficiency 5`? If the tool the player is holding is not compatible, it won't work. ShopGUIPlus has this feature, for example.

**Comment by TinyTank800** [comment]
the only way to do this currently is for a player to hold an item out and use placeholders to check if they are holding a tool or use the new movable items kinda like the composter but instead make it so when they put an unenchanted sword in it would give then the enchanted sword.

**Comment by KickSquareMC** [comment]
Alright. Thanks
