### ISSUE TITLE
recognize scoreboard and team

### ISSUE THREAD

**Issue by Dre4mur** [rockyhawk64/CommandPanels#90]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
No

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Describe the Issue

Is it possible to use the values ​​of a scoreboard or being within a team (Minecraft Vanilla commands) to perform conditions with hassperm / hassvalue?

### Expected behavior

I want to make that through a scoreboard value or belonging to a team, the condition is activated to be able to tp to a certain place.

### Versions:
 - Minecraft: 1.16.4
 - CommandPanels: 3.14.4

**Comment by fireFerry** [comment]
Yes this is possible using placeholders.
