### ISSUE TITLE
New Placeholder

### ISSUE THREAD

**Issue by ArabianPandaMC** [rockyhawk64/CommandPanels#93]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.

I want to create some sort of ban panel, I want some sort of new placeholder where for example if you type /gban <argue>, you get that argue as an placeholder like /banip {argue} 

### Describe the solution you'd like

I want some sort of new placeholder where for example if you type /gban <argue>, you get that argue as an placeholder like /banip {argue

### Describe alternatives you've considered

I'm currently using the placeholder that lets you put in your placeholder after the action.

### Additional context

Nope

**Comment by fireFerry** [comment]
Already there, look at the wiki on panel variables
