### ISSUE TITLE
Panel items appear in the user inventory

### ISSUE THREAD

**Issue by Robypelle** [rockyhawk64/CommandPanels#94]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
fastclicking or sometimes just clicking an item in a panel makes it appear in the user inventory (with other items of the same panel). the items appearing in the user inventory are real, not a visual glitch.

### To Reproduce
1. open a panel in game
2. Click fast on an icon that doesn't have any effect
3. close the panel
4. open the player inventory (items might appear after a few tries of opening and closing the player's inventory)

### Expected behavior
clicking an item that doesn't open a new panel or runs a command should do nothing, the item should be immovable. closing the panel and then opening the player's inventory should show a normal looking inventory, no items should appear, especially items that were used in the previous command panel

### Screenshots/videos
player inventory before the bug
(https://media.discordapp.net/attachments/792824922313195520/794735121886085130/unknown.png)

opening the userpanel (a panel)
(https://media.discordapp.net/attachments/792824922313195520/794735514301235200/unknown.png)

head and panes used in the panel are now visible in the crafting area of the player's inventory. those items are not a visual glitch, closing the inventory drops those items, and are movable in the other slots of the inventory.
(https://media.discordapp.net/attachments/792824922313195520/794735361674313758/unknown.png)

### Versions:
 - Minecraft: 1.16.4 (paper-1.16.4-332)
 - CommandPanels: 3.14.4.5

### Additional context/Panel files
config.yml https://pastebin.com/Lyrt6Py2
userpanel.yml https://pastebin.com/LJSWxeuh
i've been having this issue for a few days already, one of my players found it, he showed me and a bunch of other players, and we all got affected. some of my panels have bedrock as icon, and someone even got that in their inventory

**Comment by fireFerry** [comment]
You can avoid this by adding `cpc` as a command to the items and adding a cooldown to open the menu

**Comment by Robypelle** [comment]
bu

> 
> 
> You can avoid this by adding `cpc` as a command to the items and adding a cooldown to open the menu

but the bug works also when clicking on items that don't run any kind of command

**Comment by fireFerry** [comment]
> > You can avoid this by adding `cpc` as a command to the items and adding a cooldown to open the menu
> 
> but the bug works also when clicking on items that don't run any kind of command

That's why you add the command `cpc` to those items.

**Comment by rockyhawk64** [comment]
I have been trying to replicate the error using the CommandPanels server and my own test server (to account for higher ping). I have not been able to yet replicate it.
Are you able to do `/cpd`, and see if any errors show up in the console after the problem occurs?
Also if you do F3+H. Are you able to tell me how many NBT tags each of the items have? The NBT tags will be in the lore of the item when Advanced Tooltips is enabled.

**Comment by Robypelle** [comment]
most of the items have 3 NBT tags, some 4 and some 5.
i used the cpc command in all decorative slots, and i thought it fixed it, but one player still got items in his inventory. i'm trying now to reproduce the bug in debug mode to see if any errors appear

**Comment by rockyhawk64** [comment]
I have released a new update I was not able to replicate the issue but hopefully this will solve some of the issue,
https://github.com/rockyhawk64/CommandPanels/releases/tag/3.14.4.6
If the problem happens again the items will essentially be visual glitches only.

**Comment by Robypelle** [comment]
thanks a lot, really appreciated!
i'll test it as much as possible

**Comment by rockyhawk64** [comment]
Closing issue.
