### ISSUE TITLE
Can't cancel commands if one doesn't work? Any way to implement logic?

### ISSUE THREAD

**Issue by SamHammermaster** [rockyhawk64/CommandPanels#95]
I am creating a Rankup system through command panels
The player does /rankup to get a menu of the ranks.
They have permission to click on the next rank in the track for them
A new command panel gets pulled up that says confirm or cancel
If they confirm, the money is taken from them and they are promoted, the only issue is that I cannot figure out how to not promote them if they do not have enough money. It will say "Insufficient funds!" then still go on to promote them. Is there any way to implement basic logic like if(hasEnoughMoney()) then promote, else don't?
![image](https://user-images.githubusercontent.com/72102854/103722090-37d38180-4f9d-11eb-81d2-897e5ebe1ed8.png)

Thanks

**Comment by TinyTank800** [comment]
Use paywall= amount to charge them. If you don't have the money the commands below won't run. You can also use hasperm and hasgreater to check those things and display if they have the perm or enough money.

**Comment by TinyTank800** [comment]
[TinyRankup.zip](https://github.com/rockyhawk64/CommandPanels/files/5773663/TinyRankup.zip)
If you want an example on how to do it.
