### ISSUE TITLE
Item Paywall with full inventory doesnt give items

### ISSUE THREAD

**Issue by MeerBiene** [rockyhawk64/CommandPanels#96]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No, I felt a github issues makes more sense

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug

If you buy something with an item paywall and should receive an item (the commands i used is "console= give %cp-player-name% SOMETHING 1") the item used for paying is removed from your inventory but you dont get the new item

### To Reproduce
1. use the commands item-paywall and give
2. have essentials installed
3. have a full inventory

### Expected behavior

I dont know if this issue can be resolved with CP, maybe add a full inventory check or something.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: 1.16.5
 - CommandPanels: 3.15.1.2

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

**Comment by fireFerry** [comment]
This seems to be an essentials thing rather then a cp issue. Essentials doesn't give the item if your inventory is full.

**Comment by MeerBiene** [comment]
Okay yeah that fixed it thank you very much. Will close the issue if thats fine for you guys?

**Comment by TheLonelyWolf1** [comment]
Good to hear, that your problem is solved. I'm closing this now :)
Should new problems arise, you can create an issue here or a ticket in discord ;)
