### ISSUE TITLE
Item for panel

### ISSUE THREAD

**Issue by Gayytis** [rockyhawk64/CommandPanels#97]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No
### Describe the solution you'd like

This would be to create an option in the open-with-item category that would allow the menu item to be given back at each connection but the item would be disposable, removable, replaceable, etc.
Not quite like the "stationary" that already exists because it prevents the item from being moved or deleted without a command like /clearinventory.

**Comment by fireFerry** [comment]
You can use a plugin that executes commands on join, and then execute the `/cp <panelname> item` command.

**Comment by rockyhawk64** [comment]
The commandpanel items will only have two states, stationary where they cannot be moved and another where they can be moved but will only be given via command at this time.
