### ISSUE TITLE
Sign Input!

### ISSUE THREAD

**Issue by Justsean2** [rockyhawk64/CommandPanels#98]
It would be really nice if  y'all added a placeholder like %cp-player-sign-input% where instead of using chat to input a value you can have players use a sign to input a variable!

**Comment by fireFerry** [comment]
Hello, please use the format provided next time, issues without the format will be less prioritised.

**Comment by Justsean2** [comment]
Uhm first off it's not an issue just a suggestion.. as well as there is a format?

**Comment by fireFerry** [comment]
They're called Github issues.
